SET IDENTITY_INSERT DocTypes ON

--Системни
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (1, 1, NULL, NULL, N'Документ', N'Document', 0, NULL, NULL, NULL, NULL, NULL, 0)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (2, 1, NULL, NULL, N'Резолюция', N'Resolution', 0, NULL, NULL, NULL, NULL, NULL, 0)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (3, 1, NULL, NULL, N'Задача', N'Task', 0, NULL, NULL, NULL, NULL, NULL, 0)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (4, 1, NULL, NULL, N'Забележка', N'Remark', 0, NULL, NULL, NULL, NULL, NULL, 0)

--Общи
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (101, 100, 4, NULL, N'Писмо', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (102, 100, 4, NULL, N'Заповед', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)

--Услуги
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (201, 201, 4, 4, N'Издаване на оперативен лиценз на въздушен превозвач', N'R-4686', 1, N'0010-004686', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (202, 201, 4, 4, N'Издаване на свидетелство за авиационен оператор, извършващ търговски превози на пътници и товари', N'R-5090', 1, N'0010-005090', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (203, 201, 4, 4, N'Издаване на свидетелство за авиационен оператор, извършващ специализирани авиационни работи', N'R-5000', 1, N'0010-005000', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (204, 201, 4, 4, N'Издаване на свидетелство за професионално обучение на авиационен учебен център', N'R-4834', 1, N'0010-004834', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (205, 201, 4, 4, N'Издаване на свидетелство за правоспособност на авиационен персонал – пилоти', N'R-4186', 1, N'0010-004186', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (206, 201, 4, 4, N'Издаване на свидетелство за правоспособност на авиационен персонал – членове на летателния състав от екипажите на ВС, различни от пилоти', N'R-4244', 1, N'0010-004244', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (207, 201, 4, 4, N'Издаване на свидетелство за правоспособност на членовете на кабинния екипаж', N'R-4864', 1, N'0010-004864', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (208, 201, 4, 4, N'Издаване на свидетелство за правоспособност на авиационен персонал – полетни диспечери', N'R-4242', 1, N'0010-004242', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (209, 201, 4, 4, N'Издаване на свидетелство за правоспособност за техническо обслужване на самолети и хеликоптери', N'R-4240', 1, N'0010-004240', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (210, 201, 4, 4, N'Признаване на свидетелство за правоспособност на чужди граждани', N'R-4296', 1, N'0010-004296', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (211, 201, 4, 4, N'Издаване на удостоверение за одобрение за ползване на авиационен тренажор', N'R-4900', 1, N'0010-004900', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (212, 201, 4, 4, N'Издаване на разрешително за проверяващ', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (213, 201, 4, 4, N'Издаване на свидетелство за одобрение на организация за обучение', N'R-4860', 1, N'0010-004860', NULL, NULL, NULL, NULL, 1)
<<<<<<< HEAD
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (214, 201, 4, 4, N'Издаване на удостоверение за одобрение на организация за обучение, намираща се в друга държава', N'R-4862', 1, N'0010-004862', NULL, NULL, NULL, NULL, 1)
=======
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (214, 201, 4, 4, N'Издаване на удостоверение за одобрение на организация за обучение, намираща се в друга държава', N'', 1, N'0010-004862', NULL, NULL, NULL, NULL, 1)
>>>>>>> Add ExcelConfig.tt
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (215, 201, 4, 4, N'Издаване на удостоверение за регистрация на ВС', N'R-4356', 1, N'0010-004356', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (216, 201, 4, 4, N'Издаване на свидетелство за правоспособност на ръководители на полети, на ученик-ръководители на полети, на асистент-координатори на полети и на координатори по УВД', N'R-4284', 1, N'0010-004284', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (217, 201, 4, 4, N'Издаване на свидетелство за правоспособност на инженерно-технически състав, извършващ техническо обслужване на средствата за управление на въздушното движение', N'R-4958', 1, N'0010-004958', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (218, 201, 4, 4, N'Издаване на свидетелство за преподавател към авиационни учебни центрове', N'R-4824', 1, N'0010-004824', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (219, 201, 4, 4, N'Издаване на свидетелство на доставчик на аеронавигационно обслужване', N'R-4738', 1, N'0010-004738', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (220, 201, 4, 4, N'Издаване на свидетелство за експлоатационна годност на автоматизираните системи за УВД', N'R-4764', 1, N'0010-004764', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (221, 201, 4, 4, N'Издаване на свидетелства за експлоатационна годност на навигационните съоръжения за въздушна навигация и кацане', N'R-4766', 1, N'0010-004766', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (222, 201, 4, 4, N'Издаване на удостоверение за експлоатационна годност на граждански летища', N'R-4588', 1, N'0010-004588', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (223, 201, 4, 4, N'Издаване на удостоверение за експлоатационна годност на летателни площадки', N'R-4590', 1, N'0010-004590', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (224, 201, 4, 4, N'Издаване на удостоверение за експлоатационна годност на системи и съоръжения за наземно обслужване', N'R-4614', 1, N'0010-004614', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (225, 201, 4, 4, N'Издаване на лиценз на летищен оператор', N'R-4598', 1, N'0010-004598', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (226, 201, 4, 4, N'Издаване на лиценз на оператор по наземно обслужване или самообслужване на летище', N'R-4606', 1, N'0010-004606', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (227, 201, 4, 4, N'Издаване на удостоверение  за одобрение на организация за управление на поддържане на постоянна летателна годност (EASA Form 14)', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (228, 201, 4, 4, N'Издаване на удостоверение за одобрение на организация за техническо обслужване (EASA Form 3F)', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (229, 201, 4, 4, N'Издаване на удостоверение за одобрение на организация за техническо обслужване (EASA Form 3)', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (230, 201, 4, 4, N'Издаване на одобрение за производствена организация', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (231, 201, 4, 4, N'Издаване на удостоверение за одобрение на организация за обучение и изпит-ване на персонал за техническо обслужване (EASA Form 11)', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (232, 201, 4, 4, N'Издаване на лиценз за техническо обслужване и ремонт на авиационна техника (за въздухоплавателни средства извън обхвата на Регламент (ЕО) № 216/2008 на Европейския парламент и Съвета от 20 февруари 2008 година относно общи правила в областта на гражданското въздухоплаване, за създаване на Европейска агенция за авиационна безопасност - включени в Приложение ІІ на Регламента)', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (233, 201, 4, 4, N'Издаване на медицинско свидетелство на авиационния персонал', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (234, 201, 4, 4, N'Издаване на удостоверение за летателна годност на ВС', N'R-4470', 1, N'0010-004470', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (235, 201, 4, 4, N'Издаване на удостоверение за преглед на летателна годност (EASA Form 15a)', N'R-4544', 1, N'0010-004544', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (236, 201, 4, 4, N'Издаване на удостоверение за съответствие с нормите за авиационен шум', N'R-4514', 1, N'0010-004514', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (237, 201, 4, 4, N'Издаване на документ за съгласие за производство от производствена организация без одобрение', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
<<<<<<< HEAD
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (238, 201, 4, 4, N'Издаване и поддържане на сертификат за компетентност на лица, изпълняващи задачи по проверка и контрол за сигурност в гражданското въздухоплаване', N'R-4810', 1, N'0010-004810', NULL, NULL, NULL, NULL, 1)
=======
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (238, 201, 4, 4, N'Издаване и поддържане на сертификат за компетентност на лица, изпълняващи задачи по проверка и контрол за сигурност в гражданското въздухоплаване', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
>>>>>>> Add ExcelConfig.tt
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (239, 201, 4, 4, N'Издаване на Разрешително за ползване на радиостанция на въздухоплавателно средство', N'R-4490', 1, N'0010-004490', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (240, 201, 4, 4, N'Издаване на Удостоверение за отписване от Регистъра на ВС', N'R-4396', 1, N'0010-004396', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (241, 201, 4, 4, N'Издаване на експортно удостоверение за летателна годност', N'R-4566', 1, N'0010-004566', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (242, 201, 4, 4, N'Издаване на Специално удостоверение за ЛГ за любителски построено ВС', N'R-4578', 1, N'0010-004578', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (243, 201, 4, 4, N'Издаване на разрешение за полет', N'R-4926', 1, N'0010-004926', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (244, 201, 4, 4, N'Издаване на Одобрение на ръководен персонал     ( EASA Form 4)  за всички одобрени организации', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (245, 201, 4, 4, N'Издаване на Одобрение на описание на организация за управление поддържането на постоянна летателна годност', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (246, 201, 4, 4, N'Издаване на Одобрение на описание на организация за техническо обслужване', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (247, 201, 4, 4, N'Издаване на Одобрение на ръководство за техническо обслужване на организация', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (248, 201, 4, 4, N'Издаване на Одобрение на описание на организация за техническо обслужване (на Организации по Наредба № 145)', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (249, 201, 4, 4, N'Издаване на Одобрение на описание на организация за обучение на персонал за техническо обслужване на ВС', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (250, 201, 4, 4, N'Издаване на Одобрение на технически борден дневник – по типове ВС', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (251, 201, 4, 4, N'Издаване на Одобрение на програма за техническо обслужване на ВС – за всяко ВС', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (252, 201, 4, 4, N'Назначаване на S-Mode код (24 битов адрес на ВС)', N'R-4378', 1, N'0010-004378', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (253, 201, 4, 4, N'Вписване и отписване в Регистъра на гражданските въздухоплавателни средства в Република България на залози и запори', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (254, 201, 4, 4, N'Продължаване срока на валидност, изменение и анулиране на издаваните лицензи, свидетелства, удостоверения, сертификати и одобрения.', N'', 0, NULL, NULL, NULL, NULL, NULL, 1)

--Отговори на услуги
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (401, 300, NULL, NULL, N'Съобщение, че получаването не се потвърждава', N'ReceiptNotAcknowledgedMessage', 1, N'0010-000001', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (402, 300, NULL, NULL, N'Съобщение, че получаването се потвърждава', N'ReceiptAcknowledgedMessage', 1, N'0010-000002', NULL, NULL, NULL, NULL, 1)
INSERT [dbo].[DocTypes] ([DocTypeId], [DocTypeGroupId], [PrimaryRegisterIndexId], [SecondaryRegisterIndexId], [Name], [Alias], [IsElectronicService], [ElectronicServiceFileTypeUri], [ElectronicServiceTypeApplication], [ElectronicServiceProvider], [ExecutionDeadline], [RemoveIrregularitiesDeadline], [IsActive]) VALUES (403, 300, NULL, NULL, N'Указания за отстраняване на нередовности', N'RemovingIrregularitiesInstructions', 1, N'0010-003010', NULL, NULL, NULL, NULL, 1)


SET IDENTITY_INSERT DocTypes OFF





