SET IDENTITY_INSERT DocTypes ON

--Системни
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (1, 1, 0, N'Документ', N'Document', 0)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (2, 1, 0, N'Резолюция', N'Resolution', 0)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (3, 1, 0, N'Задача', N'Task', 0)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (4, 1, 0, N'Забележка', N'Remark', 0)

--Общи
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, PrimaryRegisterIndexId, IsElectronicService, Name, Alias, IsActive) VALUES (101, 100, 4, 0, N'Писмо', N'', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, PrimaryRegisterIndexId, IsElectronicService, Name, Alias, IsActive) VALUES (102, 100, 4, 0, N'Заповед', N'', 1)

--Искане
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (201, 201, 0, 'PPL(A)- Заявление за издаване/замяна на свидетелство за пилот (самолет) по JAR-FCL, въз основа на издадено свидетелство по реда на Наредба №1','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (202, 201, 0, 'ЗАЯВЛЕНИЕ ЗА ТЕОРЕТИЧЕН ИЗПИТ ЗА ТРАНСПОРТЕН ПИЛОТ НА САМОЛЕТ - JAR-FCL','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (203, 201, 0, 'ЗАЯВЛЕНИЕ ЗА ТЕОРЕТИЧЕН ИЗПИТ ЗА ПРОФЕСИОНАЛЕН ПИЛОТ НА САМОЛЕТ - JAR-FCL','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (204, 201, 0, 'ЗАЯВЛЕНИЕ ЗА ТЕОРЕТИЧЕН ИЗПИТ ЗА ПОЛЕТИ ПО ПРИБОРИ (САМОЛЕТ / ВЕРТОЛЕТ) - JAR-FCL','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (205, 201, 0, 'Заявление за издаване/замяна на свидетелство за пилот (самолет) по JAR-FCL, въз основа на издадено свидетелство по реда на Наредба №1','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (206, 201, 0, 'Заявление за издаване/замяна на свидетелство за пилот (самолет) по JAR-FCL, въз основа на издадено свидетелство по реда на Наредба №1','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (207, 201, 0, 'Заявление за издаване/замяна на свидетелство за пилот (самолет) по JAR-FCL, въз основа на издадено свидетелство по реда на Наредба №1','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (208, 201, 0, 'ЗАЯВЛЕНИЕ ЗА ТЕОРЕТИЧЕН ИЗПИТ ЗА ПРОФЕСИОНАЛЕН ПИЛОТ НА САМОЛЕТ - JAR-FCL','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (209, 201, 0, 'Заявление за издаване/вписване на квалификационен клас/подквалификационен клас/преидаване/подмяна/замяна/премахване на ограничения на свидетелство за правоспособност на ATSML','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (210, 201, 0, 'Заявление за Летателна проверка за издаване на ATPL(H)/IR съгласно JAR-FCL','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (211, 201, 0, 'СПРАВКА ЗА ДОП. ОБУЧЕНИЕ ПРИ КРЕДИТИРАНЕ НА БАЗОВО ОБРАЗОВАНИЕ ПРИ ПЪРВ. ИЗДАВАНЕ НА СП НА АВИАЦИОНЕН ТП ИЛИ ПРИРАВНЯВАНЕ НА НАЦИОНАЛНО СП ЗА ОБУЧЕНИЕ КЪМ СТАНДАРТА В ДОП. 1 КЪМ ПР. ІІІ ЧАСТ66,РЕГ. 2042/2003 СЪГЛАСНО ОБОБЩЕН  ДОКЛАД ЗА КОНВ. И КРЕД. ','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (212, 201, 0, 'СПРАВКА ЗА ДОПЪЛНИТЕЛНО ОБУЧЕНИЕ ПРИ КОНВЕТИРАНЕ / РАЗШИРЕНИЕ НА СВИДЕТЕЛСТВА ЗА ПРАВОСПОСОБНОСТ НА АВИАЦИОНЕН ТЕХНИЧЕСКИ ПЕРСОНАЛ ПО СТАНДАРТА В ДОПЪЛНЕНИЕ 1 КЪМ ПРИЛОЖЕНИЕ ІІІ  ЧАСТ 66 ОТ РЕГЛАМЕНТ 2042/2003','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (213, 201, 0, 'Заявление за чужди проверяващи','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (214, 201, 0, 'Заявление за издаване на свидетелство за правоспособност на ученик SATC','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (215, 201, 0, 'Заявление за вписване/заличаване на квалификационен клас и/или разрешение ATC','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (216, 201, 0, 'Заявление за продължаване срока на валидност на квалификационни класове и/или разрешения вписани в свидетелството ATC','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (217, 201, 0, 'Заявление за възстановяване на квалификационни класове и/или разрешения ATC','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (218, 201, 0, 'Заявление за замяна на валидно свидетелство за правоспособност ATC','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (219, 201, 0, 'Заявление за издаване на свидетелство за правоспособност CATM','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (220, 201, 0, 'Заявление за вписване/заличаване на разрешение към свидетелство за правоспособност CATM','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (221, 201, 0, 'Заявление за продължаване срока на валидност на разрешение към свидетелство за правоспособност CATM','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (222, 201, 0, 'Заявление за възстановяване на разрешение към свидетелство за правоспособност CATM','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (223, 201, 0, 'Заявление за замяна на валидно свидетелство за правоспособност CATM','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (224, 201, 0, 'Заявление за издаване на свидетелство за правоспособност FDA','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (225, 201, 0, 'Заявление за вписване/заличаване на разрешение към свидетелство за правоспособност FDA','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (226, 201, 0, 'Заявление за продължаване срока на валидност на разрешение към свидетелство за правоспособност FDA','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (227, 201, 0, 'Заявление за възстановяване на разрешение към свидетелство за правоспособност FDA','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (228, 201, 0, 'Заявление за замяна на валидно свидетелство за правоспособност FDA','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (229, 201, 0, 'Заявление за преиздаване на свидетелство за правоспособност ATC, CATM, FDA','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (230, 201, 0, 'Заявление за първоначално издаване / изменение / конвертиране / премахване на ограничения / подновяване / спиране, временно отстраняване или ограничаване на СВИДЕТЕЛСТВО ЗА ПРАВОСПОСОБНОСТ ЗА ТО (AML) съгласно Part-66','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (231, 201, 0, 'Заявление за одобрение по Част-M подчаст-G, първоначално','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (232, 201, 0, 'Заявление за одобрение по Част-M подчаст-F, първоначално','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (233, 201, 0, 'Заявление за одобрение по Част-145, първоначално','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (234, 201, 0, 'Заявление за одобрение по Част-147, първоначално','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (235, 201, 0, 'Заявление за регистрация на гражданско ВС','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (236, 201, 0, 'Заявление за „Удостоверение за Преглед на Летателна Годност” (издаването / продължаване валидността)','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (237, 201, 0, 'Заявление за издаване на Удостоверение за съответсвие с нормите за авиационен шум','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (238, 201, 0, 'Заявление за разрешение за полет','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (239, 201, 0, 'Заявление за одобрение на условия за полет','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (240, 201, 0, 'Анулиране на регистрация на самолет','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (241, 201, 0, 'Заявление за издаване на експортно удостоверение','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (242, 201, 0, 'Заявление за одобрение по Част-M подчаст-G, промяна','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (243, 201, 0, 'Заявление за одобрение по Част-M подчаст-F, промяна','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (244, 201, 0, 'Заявление за одобрение по Част-145, промяна','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (245, 201, 0, 'Заявление за одобрение по Част-147, промяна','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (246, 201, 0, 'Заявление за издаване на свидетелство за правоспособност ATC','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (247, 201, 0, 'Заявление 1 - за издаване на свидетелство за правоспособност – любители пилоти','', 1)
--INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (248, 201, 0, 'Заявление 2 - за издаване на свидетелство за правоспособност на професионален пилот, транспортен пилот и правоспособност за полети по ППП','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive, PrimaryRegisterIndexId, SecondaryRegisterIndexId, ElectronicServiceFileTypeUri) VALUES (248, 201, 1, 'Заявление 2 - за издаване на свидетелство за правоспособност на професионален пилот, транспортен пилот и правоспособност за полети по ППП','R-4186', 1, 4, 4, '0010-004186')
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (249, 201, 0, 'Заявление 3 - За издаване на свидетелство за правоспособност на членове на екипажа различни от пилоти','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (250, 201, 0, 'Заявление 9 - за замяна и подмяна на валидно свидетелство за правоспособност – пилоти','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (251, 201, 0, 'Заявление 10 - за замяна и подмяна на валидно свидетелство за правоспособност на членове на екипажа различни от пилоти','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (252, 201, 0, 'Заявление 11 - за летателно обучение като обучаем и вписване на квалификационен клас , клас/тип ВС - пилоти ','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (253, 201, 0, 'Заявление 12 - за летателно обучение като обучаем и вписване на квалификационен клас , клас/тип ВС - на членове на екипаж, различни от пилоти','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (254, 201, 0, 'Заявление13 - за потвърждаване на квалификационен клас - членове на екипажа','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (255, 201, 0, 'Заявление 14 - за явяване на теоретичен изпит','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (256, 201, 0, 'Заявление 15 - за преиздаване на свидетелство за правоспособност','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (257, 201, 0, 'Заявление за признаване на валидността на свидетелство за правоспособност на пилот, издадено от друга държава за работа в състава на екипажа на ВС, регистрирано в Република България','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (258, 201, 0, 'Заявление за издаване на удостоверение за летателно обучение на пилоти','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (259, 201, 0, 'Писмо за учредяване на залог / ипотека','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (260, 201, 0, 'Заявление за издаване на свидетелство за правоспособност, потвърждаване и вписване на квалификационни класове-Полетен диспечер','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (261, 201, 0, 'Заявление за издаване/вписване на квалификационен клас/подквалификационен клас/преиздаване/подмяна/замяна/премахване на ограничения за свидетелство за правоспособност за ТО (AML)','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (262, 201, 0, 'Писмо за заличаване на залог / ипотека','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (263, 201, 0, 'Заявление за одобрение на документи на организацията','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (264, 201, 0, 'ЗАЯВЛЕНИЕ ЗА ТЕОРЕТИЧЕН ИЗПИТ ЗА ТРАНСПОРТЕН ПИЛОТ НА ВЕРТОЛЕТ','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (265, 201, 0, 'ЗАЯВЛЕНИЕ ЗА ТЕОРЕТИЧЕН ИЗПИТ ЗА ТРАНСПОРТЕН ПИЛОТ НА ВЕРТОЛЕТ И ПОЛЕТИ ПО ПРИБОРИ - JAR-FCL','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (266, 201, 0, 'Заявление за TRI и SFI инструктор','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (267, 201, 0, 'Заявление за първоначално издаване / изменение / конвертиране / премахване на ограничения / подновяване / спиране, временно отстраняване или ограничаване на СВИДЕТЕЛСТВО ЗА ПРАВОСПОСОБНОСТ ЗА ТО (AML) съгласно Part-66','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (268, 201, 0, 'Заявление за издаване/замяна на свидетелство за пилот (самолет) по JAR-FCL, въз основа на издадено свидетелство по реда на Наредба №1','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (269, 201, 0, 'Заявление за издаване/замяна на свидетелство за пилот (самолет) по JAR-FCL, въз основа на издадено свидетелство по реда на Наредба №1','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (270, 201, 0, 'Заявление за издаване/замяна на свидетелство за пилот (самолет) по JAR-FCL, въз основа на издадено свидетелство по реда на Наредба №1','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (271, 201, 0, 'Заявление за Летателна проверка за издаване на ATPL(A) съгласно JAR-FCL','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (272, 201, 0, 'Заявление за Летателна проверка за издаване на ATPL(H) съгласно JAR-FCL','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (273, 201, 0, 'Заявление за Летателна проверка за издаване на CPL(A) съгласно JAR-FCL','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (274, 201, 0, 'Заявление за Летателна проверка за издаване на CPL(H) съгласно JAR-FCL ','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (275, 201, 0, 'Заявление за Летателна проверка за издаване на IR(A) съгласно JAR-FCL','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (276, 201, 0, 'Заявление за Летателна проверка за издаване на IR(H) съгласно JAR-FCL','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (277, 201, 0, 'Заявление за Летателна проверка за издаване на CPL(A)/IR(A) съгласно JAR-FCL','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (278, 201, 0, 'Заявление за Летателна проверка за издаване на CPL(H)/IR(H) съгласно JAR-FCL','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (279, 201, 0, 'PPA без IR - Заявление за замяна на свидетелство на пилот(самолет/вертолет) издадено по реда на JAR-FCL1%2 със свидетелство за правоспособност в съответствие с PART-FCL/Рег.1178/11','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (280, 201, 0, 'PPA с IR - Заявление за замяна на свидетелство на пилот(самолет/вертолет) издадено по реда на JAR-FCL1%2 със свидетелство за правоспособност в съответствие с PART-FCL/Рег.1178/11','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (281, 201, 0, 'CPA без IR - Заявление за замяна на свидетелство на пилот(самолет/вертолет) издадено по реда на JAR-FCL1%2 със свидетелство за правоспособност в съответствие с PART-FCL/Рег.1178/11','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (282, 201, 0, 'CPA с IR - Заявление за замяна на свидетелство на пилот(самолет/вертолет) издадено по реда на JAR-FCL1%2 със свидетелство за правоспособност в съответствие с PART-FCL/Рег.1178/11','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (283, 201, 0, 'ATPA - Заявление за замяна на свидетелство на пилот(самолет/вертолет) издадено по реда на JAR-FCL1%2 със свидетелство за правоспособност в съответствие с PART-FCL/Рег.1178/11','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (284, 201, 0, 'PPH без IR - Заявление за замяна на свидетелство на пилот(самолет/вертолет) издадено по реда на JAR-FCL1%2 със свидетелство за правоспособност в съответствие с PART-FCL/Рег.1178/11','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (285, 201, 0, 'PPH с IR - Заявление за замяна на свидетелство на пилот(самолет/вертолет) издадено по реда на JAR-FCL1%2 със свидетелство за правоспособност в съответствие с PART-FCL/Рег.1178/11','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (286, 201, 0, 'CPH без IR - Заявление за замяна на свидетелство на пилот(самолет/вертолет) издадено по реда на JAR-FCL1%2 със свидетелство за правоспособност в съответствие с PART-FCL/Рег.1178/11','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (287, 201, 0, 'CPH с IR - Заявление за замяна на свидетелство на пилот(самолет/вертолет) издадено по реда на JAR-FCL1%2 със свидетелство за правоспособност в съответствие с PART-FCL/Рег.1178/11','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (288, 201, 0, 'ATPH без IR - Заявление за замяна на свидетелство на пилот(самолет/вертолет) издадено по реда на JAR-FCL1%2 със свидетелство за правоспособност в съответствие с PART-FCL/Рег.1178/11','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (289, 201, 0, 'ATPH с IR - Заявление за замяна на свидетелство на пилот(самолет/вертолет) издадено по реда на JAR-FCL1%2 със свидетелство за правоспособност в съответствие с PART-FCL/Рег.1178/11','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (290, 201, 0, 'Заявление за одобрение на ръководен персонал - ЕАСА Форма 4','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (291, 201, 0, 'Заявление за издаване на удостоверение за летателна годност','', 1)
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive) VALUES (292, 201, 0, 'Application for examiner authorisation','', 1)

--Отговори на услуги
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive, PrimaryRegisterIndexId, SecondaryRegisterIndexId, ElectronicServiceFileTypeUri) VALUES (301, 300, 1, 'Съобщение, че получаването не се потвърждава','ReceiptNotAcknowledgedMessage', 1, NULL, NULL, '0010-000001')
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive, PrimaryRegisterIndexId, SecondaryRegisterIndexId, ElectronicServiceFileTypeUri) VALUES (302, 300, 1, 'Потвърждаване за получаване','ReceiptAcknowledgedMessage', 1, NULL, NULL, '0010-000002')
INSERT INTO DocTypes(DocTypeId, DocTypeGroupId, IsElectronicService, Name, Alias, IsActive, PrimaryRegisterIndexId, SecondaryRegisterIndexId, ElectronicServiceFileTypeUri) VALUES (303, 300, 1, 'Указания за отстраняване на нередовности','RemovingIrregularitiesInstructions', 1, NULL, NULL, '0010-003010')

SET IDENTITY_INSERT DocTypes OFF
