print 'Excel Insert UnitClassifications'
GO

SET IDENTITY_INSERT [UnitClassifications] ON
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(1,1,2,1);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(2,1,2,3);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(3,1,2,5);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(4,1,2,11);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(5,1,2,12);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(6,1,2,10);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(7,1,2,2);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(8,1,2,4);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(9,1,2,6);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(10,1,2,7);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(11,1,2,8);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(12,1,2,9);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(13,1,2,13);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(14,1,2,14);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(15,1,2,15);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(16,1,2,16);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(17,1,2,17);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(18,4,2,1);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(19,4,2,3);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(20,4,2,5);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(21,4,2,11);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(22,4,2,12);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(23,4,2,10);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(24,4,2,2);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(25,4,2,4);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(26,4,2,6);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(27,4,2,7);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(28,4,2,8);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(29,4,2,9);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(30,4,2,13);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(31,4,2,14);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(32,4,2,15);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(33,4,2,16);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(34,4,2,17);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(35,48,2,1);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(36,48,2,3);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(37,48,2,5);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(38,48,2,11);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(39,48,2,12);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(40,48,2,10);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(41,48,2,2);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(42,48,2,4);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(43,48,2,6);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(44,48,2,7);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(45,48,2,8);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(46,48,2,9);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(47,48,2,13);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(48,48,2,14);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(49,48,2,15);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(50,48,2,16);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(51,48,2,17);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(52,72,2,1);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(53,72,2,3);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(54,72,2,5);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(55,72,2,11);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(56,72,2,12);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(57,72,2,10);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(58,72,2,2);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(59,72,2,4);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(60,72,2,6);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(61,72,2,7);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(62,72,2,8);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(63,72,2,9);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(64,72,2,13);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(65,72,2,14);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(66,72,2,15);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(67,72,2,16);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(68,72,2,17);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(69,3,3,1);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(70,3,3,10);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(71,3,3,11);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(72,3,3,12);
SET IDENTITY_INSERT [UnitClassifications] OFF
GO

