print 'Excel Insert UnitClassifications'
GO

SET IDENTITY_INSERT [UnitClassifications] ON
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(1,1,2,1);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(2,1,2,3);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(3,1,2,5);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(4,1,2,11);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(5,1,2,12);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(6,1,2,10);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(7,1,2,2);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(8,1,2,4);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(9,1,2,6);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(10,1,2,7);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(11,1,2,8);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(12,1,2,9);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(13,1,2,13);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(14,1,2,14);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(15,1,2,15);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(16,1,2,16);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(17,1,2,17);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(18,4,2,1);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(19,4,2,3);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(20,4,2,5);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(21,4,2,11);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(22,4,2,12);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(23,4,2,10);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(24,4,2,2);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(25,4,2,4);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(26,4,2,6);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(27,4,2,7);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(28,4,2,8);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(29,4,2,9);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(30,4,2,13);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(31,4,2,14);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(32,4,2,15);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(33,4,2,16);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(34,4,2,17);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(35,42,2,1);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(36,42,2,3);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(37,42,2,5);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(38,42,2,11);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(39,42,2,12);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(40,42,2,10);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(41,42,2,2);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(42,42,2,4);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(43,42,2,6);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(44,42,2,7);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(45,42,2,8);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(46,42,2,9);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(47,42,2,13);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(48,42,2,14);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(49,42,2,15);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(50,42,2,16);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(51,42,2,17);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(52,66,2,1);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(53,66,2,3);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(54,66,2,5);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(55,66,2,11);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(56,66,2,12);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(57,66,2,10);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(58,66,2,2);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(59,66,2,4);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(60,66,2,6);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(61,66,2,7);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(62,66,2,8);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(63,66,2,9);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(64,66,2,13);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(65,66,2,14);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(66,66,2,15);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(67,66,2,16);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(68,66,2,17);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(69,3,3,1);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(70,3,3,10);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(71,3,3,11);
INSERT INTO [UnitClassifications]([UnitClassificationId],[UnitId],[ClassificationId],[ClassificationPermissionId])VALUES(72,3,3,12);
SET IDENTITY_INSERT [UnitClassifications] OFF
GO

