INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (1  ,N'Полове'                                                                 ,N'gender'                             )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (2  ,N'Държави'                                                                ,N'countries'                          )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (3  ,N'Населени места'                                                         ,N'cities'                             )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (4  ,N'Типове адреси'                                                          ,N'addressTypes'                       )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (5  ,N'Типове персонал'                                                        ,N'staffTypes'                         )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (6  ,N'Категории персонал'                                                     ,N'employmentCategories'               )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (7  ,N'Степени на образование'                                                 ,N'graduations'                        )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (8  ,N'Учебни заведения'                                                       ,N'schools'                            )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (9  ,N'Направления'                                                            ,N'directions'                         )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (10 ,N'Типове документи'                                                       ,N'documentTypes'                      )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (11 ,N'Роли документи'                                                         ,N'documentRoles'                      )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (15 ,N'Типове състояния на Физичеко лице'                                      ,N'personStatusTypes'                  )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (16 ,N'Издатели на документи - Други'                                          ,N'otherDocPublishers'                 )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (17 ,N'Издатели на документи - Медицински'                                     ,N'medDocPublishers'                   )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (18 ,N'Типове ВС за екипажи'                                                   ,N'ratingTypes'                        )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (19 ,N'Групи Класове ВС за екипажи'                                            ,N'ratingClassGroups'                  )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (20 ,N'Класове ВС за екипажи'                                                  ,N'ratingClasses'                      )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (21 ,N'Подкласове ВС за екипажи'                                               ,N'ratingSubClasses'                   )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (22 ,N'Групи Разрешения към квалификация'                                      ,N'authorizationGroups'                )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (23 ,N'Разрешения към квалификация'                                            ,N'authorizations'                     )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (24 ,N'Легенда към видове(типове) правоспособност'                             ,N'licenceTypeDictionary'              )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (25 ,N'Видове(типове) правоспособност'                                         ,N'licenceTypes'                       )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (26 ,N'Индикатори на местоположение'                                           ,N'locationIndicators'                 )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (27 ,N'Държатели на ТС за ВС'                                                  ,N'aircraftTCHolders'                  )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (28 ,N'Типове ВС'                                                              ,N'aircraftTypes'                      )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (29 ,N'Групи ВС'                                                               ,N'aircraftTypeGroups'                 )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (30 ,N'Категория за АМЛ (Part-66 Category)'                                    ,N'aircraftGroup66'                    )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (31 ,N'Клас (Part-66 Category)'                                                ,N'aircraftClases66'                   )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (32 ,N'Ограничения (Part-66)'                                                  ,N'limitations66'                      )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (33 ,N'Класове за медицинска годност'                                          ,N'medClasses'                         )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (34 ,N'Ограничения за медицинска годност'                                      ,N'medLimitation'                      )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (35 ,N'Роли в натрупан летателният опит'                                       ,N'experienceRoles'                    )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (36 ,N'Видове летателен опит'                                                  ,N'experienceMeasures'                 )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (37 ,N'Въздухоплавателни администрации'                                        ,N'caa'                                )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (38 ,N'Степени на квалификационен клас на Физическо лице'                      ,N'personRatingLevels'                 )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (39 ,N'Видове действия относно правоспособност'                                ,N'licenceActions'                     )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (40 ,N'Класификатор на организации'                                            ,N'organizationTypes'                  )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (41 ,N'Видове организации'                                                     ,N'organizationKinds'                  )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (42 ,N'Видове заявления'                                                       ,N'applicationTypes'                   )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (43 ,N'Видове плащания по заявления'                                           ,N'applicationpaymentTypes'            )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (44 ,N'Парични единици'                                                        ,N'currencies'                         )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (45 ,N'Типове одобрения'                                                       ,N'approvalTypes'                      )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (46 ,N'Състояния на одобрение'                                                 ,N'approvalStates'                     )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (47 ,N'Класове ограничения по част 147'                                        ,N'lim147classes'                      )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (48 ,N'Категория оганичения по част 147'                                       ,N'lim147ratings'                      )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (49 ,N'Ограничения по част 147'                                                ,N'lim147limitations'                  )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (50 ,N'Класове ограничения по част М/Ф и част 145'                             ,N'lim145classes'                      )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (51 ,N'Ограничения по част М/Ф и част 145'                                     ,N'lim145limitations'                  )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (52 ,N'Раздел'                                                                 ,N'auditParts'                         )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (53 ,N'Изисквания към раздел'                                                  ,N'auditPartRequirements'              )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (54 ,N'Раздел (част) в част 3 на доклад в подкрепа на'                         ,N'auditPartSections'                  )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (55 ,N'Изисквания към раздел (част) в част 3 на доклад в подкрепа на'          ,N'auditPartSectionDetails'            )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (56 ,N'Причини за одит'                                                        ,N'auditReasons'                       )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (57 ,N'Видове одит'                                                            ,N'auditTypes'                         )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (58 ,N'Състояния на одит'                                                      ,N'auditStatuses'                      )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (59 ,N'Резултати от одит'                                                      ,N'auditResults'                       )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (60 ,N'Категории ВС'                                                           ,N'aircraftCategories'                 )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (61 ,N'Производители на ВС'                                                    ,N'aircraftProducers'                  )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (62 ,N'Типове ВС - за генериране на S-Code'                                    ,N'aircraftSCodeTypes'                 )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (63 ,N'Типове връзки с ВС'                                                     ,N'aircraftRelations'                  )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (64 ,N'Типове компоненти на ВС'                                                ,N'aircraftParts'                      )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (65 ,N'Състояния на оборудване на ВС'                                          ,N'aircraftPartStatuses'               )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (66 ,N'Типове тежести върху ВС'                                                ,N'aircraftDebtTypes'                  )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (67 ,N'Класове инциденти с ВС'                                                 ,N'aircraftOccurrenceClasses'          )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (68 ,N'Типове удостоверения за ВС'                                             ,N'aircraftCertificateTypes'           )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (69 ,N'Типове опериране на ВС'                                                 ,N'aircraftOperTypes'                  )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (70 ,N'Типове типов сертификат за ВС'                                          ,N'aircraftTypeCertificateTypes'       )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (71 ,N'Причини за отписване на ВС'                                             ,N'aircraftRemovalReasons'             )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (72 ,N'Типове Летище или летателна площадка'                                   ,N'airportTypes'                       )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (73 ,N'Типове връзки с Летище или летателна площадка'                          ,N'airportRelations'                   )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (74 ,N'Типове радиооборудване на ВС'                                           ,N'aircraftRadiotypes'                 )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (75 ,N'Типове дейности на летищен оператор'                                    ,N'airportOperatorActivityTypes'       )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (76 ,N'Типове дейности на оператор по наземно обслужване или самообслужване'   ,N'groundServiceOperatorActivityTypes' )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (77 ,N'Оценки при проверка на Физическо лице'                                  ,N'personCheckRatingValues'            )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (78 ,N'Модел на квалификация на Физическо лице'                                ,N'personRatingModels'                 )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (79 ,N'Нива на владеене на английски език'                                     ,N'engLangLevels'                      )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (80 ,N'Типове документи',                                                       N'documentParts'                      )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (81 ,N'Да/Не номенклатура'                                                     ,N'boolean'                            )
INSERT INTO [dbo].[Noms] ([NomId], [Name], [Alias]) VALUES (82 ,N'Типове персонал за обучение'                                            ,N'trainingStaffTypes'                 )
GO
