//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_0007_000006
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/nomenclature/0007-000006";
	}

	[Serializable]
	public enum AdministrativeNomenclatureDocumentTypeProcessingTypeNomenclature
	{
		[XmlEnum(Name="0006-000035")] _0006_000035,
		[XmlEnum(Name="0006-000036")] _0006_000036,
		[XmlEnum(Name="0006-000037")] _0006_000037
	}


}
