//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_0007_000008
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/nomenclature/0007-000008";
	}

	[Serializable]
	public enum AISTaskStatusNomenclature
	{
		[XmlEnum(Name="0006-000047")] _0006_000047,
		[XmlEnum(Name="0006-000048")] _0006_000048,
		[XmlEnum(Name="0006-000049")] _0006_000049
	}


}
