//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_0007_000002
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/nomenclature/0007-000002";
	}

	[Serializable]
	public enum ElectronicDocumentDiscrepancyTypeNomenclature
	{
		[XmlEnum(Name="0006-000005")] _0006_000005,
		[XmlEnum(Name="0006-000006")] _0006_000006,
		[XmlEnum(Name="0006-000007")] _0006_000007,
		[XmlEnum(Name="0006-000008")] _0006_000008,
		[XmlEnum(Name="0006-000009")] _0006_000009,
		[XmlEnum(Name="0006-000010")] _0006_000010,
		[XmlEnum(Name="0006-000011")] _0006_000011
	}


}
