//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_0008_000033
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/value/0008-000033";
	}


}
