//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_0009_000100
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/0009-000100";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class MSCollection : System.Collections.Generic.List<MS>
	{
	}



	[XmlRoot(ElementName="MaritalStatusData",Namespace=Declarations.SchemaVersion,IsNullable=false),Serializable]
	[XmlType(TypeName="MaritalStatusData",Namespace=Declarations.SchemaVersion)]
	public partial class MaritalStatusData
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="versionDate",DataType="date")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DateTime? __versionDate;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __versionDateSpecified { get { return __versionDate.HasValue; } }
		
		[XmlIgnore]
		public DateTime? versionDate
		{ 
		get { return __versionDate; }
		set { __versionDate = value; }
		}
		


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(MaritalStatuses),ElementName="MaritalStatuses",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public MaritalStatuses __MaritalStatuses;
		
		[XmlIgnore]
		public MaritalStatuses MaritalStatuses
		{
			get {return __MaritalStatuses;}
			set {__MaritalStatuses = value;}
		}

		public MaritalStatusData()
		{
		}
	}


	[XmlType(TypeName="MaritalStatuses",Namespace=Declarations.SchemaVersion),Serializable]
	public partial class MaritalStatuses
	{


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(MS),ElementName="MS",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public MSCollection __MSCollection;
		
		[XmlIgnore]
		public MSCollection MSCollection
		{
			get
			{
				if (__MSCollection == null) __MSCollection = new MSCollection();
				return __MSCollection;
			}
			set {__MSCollection = value;}
		}

		public MaritalStatuses()
		{
		}
	}


	[XmlType(TypeName="MS",Namespace=Declarations.SchemaVersion),Serializable]
	public partial class MS
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="Code",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Code;
		
		[XmlIgnore]
		public string Code
		{ 
			get { return __Code; }
			set { __Code = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Name;
		
		[XmlIgnore]
		public string Name
		{ 
			get { return __Name; }
			set { __Name = value; }
		}

		public MS()
		{
		}
	}
}
