//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_0009_000161
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/0009-000161";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class ResidencePurposeCollection : System.Collections.Generic.List<ResidencePurpose>
	{
	}



	[XmlRoot(ElementName="ResidencePurposeData",Namespace=Declarations.SchemaVersion,IsNullable=false),Serializable]
	[XmlType(TypeName="ResidencePurposeData",Namespace=Declarations.SchemaVersion)]
	public partial class ResidencePurposeData
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="versionDate",DataType="date")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DateTime? __versionDate;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __versionDateSpecified { get { return __versionDate.HasValue; } }
		
		[XmlIgnore]
		public DateTime? versionDate
		{ 
		get { return __versionDate; }
		set { __versionDate = value; }
		}
		


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ResidencePurposes),ElementName="ResidencePurposes",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ResidencePurposes __ResidencePurposes;
		
		[XmlIgnore]
		public ResidencePurposes ResidencePurposes
		{
			get {return __ResidencePurposes;}
			set {__ResidencePurposes = value;}
		}

		public ResidencePurposeData()
		{
		}
	}


	[XmlType(TypeName="ResidencePurposes",Namespace=Declarations.SchemaVersion),Serializable]
	public partial class ResidencePurposes
	{


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ResidencePurpose),ElementName="ResidencePurpose",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ResidencePurposeCollection __ResidencePurposeCollection;
		
		[XmlIgnore]
		public ResidencePurposeCollection ResidencePurposeCollection
		{
			get
			{
				if (__ResidencePurposeCollection == null) __ResidencePurposeCollection = new ResidencePurposeCollection();
				return __ResidencePurposeCollection;
			}
			set {__ResidencePurposeCollection = value;}
		}

		public ResidencePurposes()
		{
		}
	}


	[XmlType(TypeName="ResidencePurpose",Namespace=Declarations.SchemaVersion),Serializable]
	public partial class ResidencePurpose
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="Code",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Code;
		
		[XmlIgnore]
		public string Code
		{ 
			get { return __Code; }
			set { __Code = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Name;
		
		[XmlIgnore]
		public string Name
		{ 
			get { return __Name; }
			set { __Name = value; }
		}

		public ResidencePurpose()
		{
		}
	}
}
