//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_0009_000006
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/0009-000006";
	}




	[XmlType(TypeName="PersonIdentifier",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class PersonIdentifier
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="EGN",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __EGN;
		
		[XmlIgnore]
		public string EGN
		{ 
			get { return __EGN; }
			set { __EGN = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="LNCh",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __LNCh;
		
		[XmlIgnore]
		public string LNCh
		{ 
			get { return __LNCh; }
			set { __LNCh = value; }
		}

		public PersonIdentifier()
		{
		}
	}
}
