//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_0009_000119
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/0009-000119";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class CitizenshipCollection : System.Collections.Generic.List<R_0009_000133.Citizenship>
	{
	}



	[XmlType(TypeName="ForeignCitizeRelativeData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class ForeignCitizeRelativeData
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_0009_000007.ForeignCitizenNames),ElementName="ForeignCitizenNames",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000007.ForeignCitizenNames __ForeignCitizenNames;
		
		[XmlIgnore]
		public R_0009_000007.ForeignCitizenNames ForeignCitizenNames
		{
			get {return __ForeignCitizenNames;}
			set {__ForeignCitizenNames = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="BirthDate",Form=XmlSchemaForm.Qualified,DataType="date",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DateTime? __BirthDate;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __BirthDateSpecified { get { return __BirthDate.HasValue; } }
		
		[XmlIgnore]
		public DateTime? BirthDate
		{ 
			get { return __BirthDate; }
			set { __BirthDate = value; }
		}
		


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="Relationship",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Relationship;
		
		[XmlIgnore]
		public string Relationship
		{ 
			get { return __Relationship; }
			set { __Relationship = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ForeignCitizeRelativeDataCitizenships),ElementName="Citizenships",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ForeignCitizeRelativeDataCitizenships __Citizenships;
		
		[XmlIgnore]
		public ForeignCitizeRelativeDataCitizenships Citizenships
		{
			get {return __Citizenships;}
			set {__Citizenships = value;}
		}

		public ForeignCitizeRelativeData()
		{
		}
	}


	[XmlType(TypeName="ForeignCitizeRelativeDataCitizenships",Namespace=Declarations.SchemaVersion),Serializable]
	public partial class ForeignCitizeRelativeDataCitizenships
	{


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_0009_000133.Citizenship),ElementName="Citizenship",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CitizenshipCollection __CitizenshipCollection;
		
		[XmlIgnore]
		public CitizenshipCollection CitizenshipCollection
		{
			get
			{
				if (__CitizenshipCollection == null) __CitizenshipCollection = new CitizenshipCollection();
				return __CitizenshipCollection;
			}
			set {__CitizenshipCollection = value;}
		}

		public ForeignCitizeRelativeDataCitizenships()
		{
		}
	}
}
