//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_0009_000064
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/0009-000064";
	}




	[XmlType(TypeName="AISTaskInitialDocument",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class AISTaskInitialDocument : R_0009_000047.RegisteredDocumentOrDocumentType
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(AISTaskInitialDocumentAdditionalData),ElementName="AdditionalData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public AISTaskInitialDocumentAdditionalData __AdditionalData;
		
		[XmlIgnore]
		public AISTaskInitialDocumentAdditionalData AdditionalData
		{
			get {return __AdditionalData;}
			set {__AdditionalData = value;}
		}

		public AISTaskInitialDocument() : base()
		{
		}
	}


	[XmlType(TypeName="AISTaskInitialDocumentAdditionalData",Namespace=Declarations.SchemaVersion),Serializable]
	public partial class AISTaskInitialDocumentAdditionalData
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAnyElement()]
		public System.Xml.XmlElement[] Any;

		public AISTaskInitialDocumentAdditionalData()
		{
		}
	}
}
