//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_0009_000091
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/0009-000091";
	}




	[XmlType(TypeName="ElectronicAdministrativeServiceURI",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class ElectronicAdministrativeServiceURI : R_0009_000022.RegisterObjectURI
	{

		public ElectronicAdministrativeServiceURI() : base()
		{
		}
	}
}
