//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_0009_000192
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/0009-000192";
	}




	[XmlType(TypeName="OfficerInDocumentStorage2",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class OfficerInDocumentStorage2 : R_0009_000027.AISUserBasicData
	{

		public OfficerInDocumentStorage2() : base()
		{
		}
	}
}
