//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_0009_000077
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/0009-000077";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class AISTaskAssessmentCollection : System.Collections.Generic.List<R_0009_000076.AISTaskAssessment>
	{
	}



	[XmlType(TypeName="AISTaskAssessmentProtocol",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class AISTaskAssessmentProtocol
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(Assessments),ElementName="Assessments",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Assessments __Assessments;
		
		[XmlIgnore]
		public Assessments Assessments
		{
			get {return __Assessments;}
			set {__Assessments = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_0009_000032.AISObjectCreationData),ElementName="ObjectCreationData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000032.AISObjectCreationData __ObjectCreationData;
		
		[XmlIgnore]
		public R_0009_000032.AISObjectCreationData ObjectCreationData
		{
			get {return __ObjectCreationData;}
			set {__ObjectCreationData = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(AISTaskAssessmentProtocolAdditionalData),ElementName="AdditionalData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public AISTaskAssessmentProtocolAdditionalData __AdditionalData;
		
		[XmlIgnore]
		public AISTaskAssessmentProtocolAdditionalData AdditionalData
		{
			get {return __AdditionalData;}
			set {__AdditionalData = value;}
		}

		public AISTaskAssessmentProtocol()
		{
		}
	}


	[XmlType(TypeName="Assessments",Namespace=Declarations.SchemaVersion),Serializable]
	public partial class Assessments
	{


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_0009_000076.AISTaskAssessment),ElementName="AssessmentData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public AISTaskAssessmentCollection __AssessmentDataCollection;
		
		[XmlIgnore]
		public AISTaskAssessmentCollection AssessmentDataCollection
		{
			get
			{
				if (__AssessmentDataCollection == null) __AssessmentDataCollection = new AISTaskAssessmentCollection();
				return __AssessmentDataCollection;
			}
			set {__AssessmentDataCollection = value;}
		}

		public Assessments()
		{
		}
	}


	[XmlType(TypeName="AISTaskAssessmentProtocolAdditionalData",Namespace=Declarations.SchemaVersion),Serializable]
	public partial class AISTaskAssessmentProtocolAdditionalData
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAnyElement()]
		public System.Xml.XmlElement[] Any;

		public AISTaskAssessmentProtocolAdditionalData()
		{
		}
	}
}
