//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_0009_000184
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/0009-000184";
	}




	[XmlType(TypeName="TouristSiteCategoryAllocationOrderNumber",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class TouristSiteCategoryAllocationOrderNumber : R_0009_000001.DocumentURI
	{

		public TouristSiteCategoryAllocationOrderNumber() : base()
		{
		}
	}
}
