//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_0009_000061
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/0009-000061";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class ClassificationSchemeAccessGrantDataAccessGrantCollection : System.Collections.Generic.List<ClassificationSchemeAccessGrantDataAccessGrant>
	{
	}



	[XmlType(TypeName="ClassificationSchemeAccessGrantData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class ClassificationSchemeAccessGrantData
	{


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ClassificationSchemeAccessGrantDataAccessGrant),ElementName="AccessGrant",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ClassificationSchemeAccessGrantDataAccessGrantCollection AccessGrantCollection { get; set; }

		public ClassificationSchemeAccessGrantData()
		{
		}
	}


	[XmlType(TypeName="ClassificationSchemeAccessGrantDataAccessGrant",Namespace=Declarations.SchemaVersion),Serializable]
	public partial class ClassificationSchemeAccessGrantDataAccessGrant
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="SchemeID",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string SchemeID { get; set; }

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="SectionID",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string SectionID { get; set; }

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_0009_000030.PositionInAdministrationOrAISUser),ElementName="UserGrantee",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000030.PositionInAdministrationOrAISUser UserGrantee { get; set; }

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(ClassificationSchemeAccessGrantDataAccessGrantSpecificParameters),ElementName="SpecificParameters",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ClassificationSchemeAccessGrantDataAccessGrantSpecificParameters SpecificParameters { get; set; }

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_0009_000032.AISObjectCreationData),ElementName="ObjectCreationData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000032.AISObjectCreationData ObjectCreationData { get; set; }

		public ClassificationSchemeAccessGrantDataAccessGrant()
		{
		}
	}


	[XmlType(TypeName="ClassificationSchemeAccessGrantDataAccessGrantSpecificParameters",Namespace=Declarations.SchemaVersion),Serializable]
	public partial class ClassificationSchemeAccessGrantDataAccessGrantSpecificParameters
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAnyElement()]
		public System.Xml.XmlElement[] Any;

		public ClassificationSchemeAccessGrantDataAccessGrantSpecificParameters()
		{
		}
	}
}
