//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_0009_000170
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/0009-000170";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class MunicipalityInformationAccessTypeCollection : System.Collections.Generic.List<string>
	{
	}



	[XmlRoot(ElementName="DocumentContainingMunicipalityInformationCopyGrantDecision",Namespace=Declarations.SchemaVersion,IsNullable=false),Serializable]
	[XmlType(TypeName="DocumentContainingMunicipalityInformationCopyGrantDecision",Namespace=Declarations.SchemaVersion)]
	public partial class DocumentContainingMunicipalityInformationCopyGrantDecision
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_0009_000003.DocumentTypeURI),ElementName="DocumentTypeURI",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000003.DocumentTypeURI __DocumentTypeURI;
		
		[XmlIgnore]
		public R_0009_000003.DocumentTypeURI DocumentTypeURI
		{
			get {return __DocumentTypeURI;}
			set {__DocumentTypeURI = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="DocumentTypeName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __DocumentTypeName;
		
		[XmlIgnore]
		public string DocumentTypeName
		{ 
			get { return __DocumentTypeName; }
			set { __DocumentTypeName = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_0009_000001.DocumentURI),ElementName="DocumentURI",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000001.DocumentURI __DocumentURI;
		
		[XmlIgnore]
		public R_0009_000001.DocumentURI DocumentURI
		{
			get {return __DocumentURI;}
			set {__DocumentURI = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="DocumentReceiptOrSigningDate",Form=XmlSchemaForm.Qualified,DataType="date",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DateTime? __DocumentReceiptOrSigningDate;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __DocumentReceiptOrSigningDateSpecified { get { return __DocumentReceiptOrSigningDate.HasValue; } }
		
		[XmlIgnore]
		public DateTime? DocumentReceiptOrSigningDate
		{ 
			get { return __DocumentReceiptOrSigningDate; }
			set { __DocumentReceiptOrSigningDate = value; }
		}
		


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_0009_000002.ElectronicServiceProviderBasicData),ElementName="ElectronicServiceProviderBasicData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000002.ElectronicServiceProviderBasicData __ElectronicServiceProviderBasicData;
		
		[XmlIgnore]
		public R_0009_000002.ElectronicServiceProviderBasicData ElectronicServiceProviderBasicData
		{
			get {return __ElectronicServiceProviderBasicData;}
			set {__ElectronicServiceProviderBasicData = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_0009_000143.MunicipalityAdministrationLocation),ElementName="MunicipalityAdministrationLocation",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000143.MunicipalityAdministrationLocation __MunicipalityAdministrationLocation;
		
		[XmlIgnore]
		public R_0009_000143.MunicipalityAdministrationLocation MunicipalityAdministrationLocation
		{
			get {return __MunicipalityAdministrationLocation;}
			set {__MunicipalityAdministrationLocation = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_0009_000073.AISCaseURI),ElementName="AISCaseURI",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000073.AISCaseURI __AISCaseURI;
		
		[XmlIgnore]
		public R_0009_000073.AISCaseURI AISCaseURI
		{
			get {return __AISCaseURI;}
			set {__AISCaseURI = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_0009_000145.MunicipalityInformationAccessRightSubject),ElementName="MunicipalityInformationAccessRightSubject",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000145.MunicipalityInformationAccessRightSubject __MunicipalityInformationAccessRightSubject;
		
		[XmlIgnore]
		public R_0009_000145.MunicipalityInformationAccessRightSubject MunicipalityInformationAccessRightSubject
		{
			get {return __MunicipalityInformationAccessRightSubject;}
			set {__MunicipalityInformationAccessRightSubject = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="NeededMunicipalityInformationDescription",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __NeededMunicipalityInformationDescription;
		
		[XmlIgnore]
		public string NeededMunicipalityInformationDescription
		{ 
			get { return __NeededMunicipalityInformationDescription; }
			set { __NeededMunicipalityInformationDescription = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="NeededMunicipalityInformationProvidedAccessLevel",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __NeededMunicipalityInformationProvidedAccessLevel;
		
		[XmlIgnore]
		public string NeededMunicipalityInformationProvidedAccessLevel
		{ 
			get { return __NeededMunicipalityInformationProvidedAccessLevel; }
			set { __NeededMunicipalityInformationProvidedAccessLevel = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="MunicipalityInformationProvidedAccessTerm",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="duration",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __MunicipalityInformationProvidedAccessTerm;
		
		[XmlIgnore]
		public string MunicipalityInformationProvidedAccessTerm
		{ 
			get { return __MunicipalityInformationProvidedAccessTerm; }
			set { __MunicipalityInformationProvidedAccessTerm = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="MunicipalityInformationAccessLocation",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __MunicipalityInformationAccessLocation;
		
		[XmlIgnore]
		public string MunicipalityInformationAccessLocation
		{ 
			get { return __MunicipalityInformationAccessLocation; }
			set { __MunicipalityInformationAccessLocation = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(DocumentContainingMunicipalityInformationCopyGrantDecisionMunicipalityInformationAccessTypes),ElementName="MunicipalityInformationAccessTypes",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DocumentContainingMunicipalityInformationCopyGrantDecisionMunicipalityInformationAccessTypes __MunicipalityInformationAccessTypes;
		
		[XmlIgnore]
		public DocumentContainingMunicipalityInformationCopyGrantDecisionMunicipalityInformationAccessTypes MunicipalityInformationAccessTypes
		{
			get {return __MunicipalityInformationAccessTypes;}
			set {__MunicipalityInformationAccessTypes = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="InformationRecordingTechnicalParameters",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __InformationRecordingTechnicalParameters;
		
		[XmlIgnore]
		public string InformationRecordingTechnicalParameters
		{ 
			get { return __InformationRecordingTechnicalParameters; }
			set { __InformationRecordingTechnicalParameters = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="MunicipalityInformationAccessExpenses",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="float",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public float __MunicipalityInformationAccessExpenses;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __MunicipalityInformationAccessExpensesSpecified;
		
		[XmlIgnore]
		public float MunicipalityInformationAccessExpenses
		{ 
			get { return __MunicipalityInformationAccessExpenses; }
			set { __MunicipalityInformationAccessExpenses = value; __MunicipalityInformationAccessExpensesSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="MunicipalityInformationAccessExpensesPaymentInfo",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __MunicipalityInformationAccessExpensesPaymentInfo;
		
		[XmlIgnore]
		public string MunicipalityInformationAccessExpensesPaymentInfo
		{ 
			get { return __MunicipalityInformationAccessExpensesPaymentInfo; }
			set { __MunicipalityInformationAccessExpensesPaymentInfo = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="OtherInformationHolders",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __OtherInformationHolders;
		
		[XmlIgnore]
		public string OtherInformationHolders
		{ 
			get { return __OtherInformationHolders; }
			set { __OtherInformationHolders = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(DocumentContainingMunicipalityInformationCopyGrantDecisionOfficial),ElementName="Official",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DocumentContainingMunicipalityInformationCopyGrantDecisionOfficial __Official;
		
		[XmlIgnore]
		public DocumentContainingMunicipalityInformationCopyGrantDecisionOfficial Official
		{
			get {return __Official;}
			set {__Official = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_0009_000004.XMLDigitalSignature),ElementName="XMLDigitalSignature",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000004.XMLDigitalSignature __XMLDigitalSignature;
		
		[XmlIgnore]
		public R_0009_000004.XMLDigitalSignature XMLDigitalSignature
		{
			get {return __XMLDigitalSignature;}
			set {__XMLDigitalSignature = value;}
		}

		public DocumentContainingMunicipalityInformationCopyGrantDecision()
		{
		}
	}


	[XmlType(TypeName="DocumentContainingMunicipalityInformationCopyGrantDecisionMunicipalityInformationAccessTypes",Namespace=Declarations.SchemaVersion),Serializable]
	public partial class DocumentContainingMunicipalityInformationCopyGrantDecisionMunicipalityInformationAccessTypes
	{


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(string),ElementName="MunicipalityInformationAccessType",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public MunicipalityInformationAccessTypeCollection __MunicipalityInformationAccessTypeCollection;
		
		[XmlIgnore]
		public MunicipalityInformationAccessTypeCollection MunicipalityInformationAccessTypeCollection
		{
			get
			{
				if (__MunicipalityInformationAccessTypeCollection == null) __MunicipalityInformationAccessTypeCollection = new MunicipalityInformationAccessTypeCollection();
				return __MunicipalityInformationAccessTypeCollection;
			}
			set {__MunicipalityInformationAccessTypeCollection = value;}
		}

		public DocumentContainingMunicipalityInformationCopyGrantDecisionMunicipalityInformationAccessTypes()
		{
		}
	}


	[XmlType(TypeName="DocumentContainingMunicipalityInformationCopyGrantDecisionOfficial",Namespace=Declarations.SchemaVersion),Serializable]
	public partial class DocumentContainingMunicipalityInformationCopyGrantDecisionOfficial
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_0009_000005.PersonNames),ElementName="PersonNames",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000005.PersonNames __PersonNames;
		
		[XmlIgnore]
		public R_0009_000005.PersonNames PersonNames
		{
			get {return __PersonNames;}
			set {__PersonNames = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_0009_000007.ForeignCitizenNames),ElementName="ForeignCitizenNames",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_0009_000007.ForeignCitizenNames __ForeignCitizenNames;
		
		[XmlIgnore]
		public R_0009_000007.ForeignCitizenNames ForeignCitizenNames
		{
			get {return __ForeignCitizenNames;}
			set {__ForeignCitizenNames = value;}
		}

		public DocumentContainingMunicipalityInformationCopyGrantDecisionOfficial()
		{
		}
	}
}
