//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace AopAttachedDocuments
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/AopAttachedDocuments";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class AopAttachedDocumentDataCollection : System.Collections.Generic.List<AopAttachedDocument.AopAttachedDocumentData>
	{
	}



	[XmlType(TypeName="AopAttachedDocumentDatasCollection",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class AopAttachedDocumentDatasCollection
	{


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(AopAttachedDocument.AopAttachedDocumentData),ElementName="AopAttachedDocumentData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public AopAttachedDocumentDataCollection AopAttachedDocumentDataCollection { get; set; }

		public AopAttachedDocumentDatasCollection()
		{
		}
	}
}
