//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4092
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4092";
	}




	[XmlType(TypeName="AeromedicalCenter",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class AeromedicalCenter
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="AeromedicalCenterCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __AeromedicalCenterCode;
		
		[XmlIgnore]
		public string AeromedicalCenterCode
		{ 
			get { return __AeromedicalCenterCode; }
			set { __AeromedicalCenterCode = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="AeromedicalCenterName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __AeromedicalCenterName;
		
		[XmlIgnore]
		public string AeromedicalCenterName
		{ 
			get { return __AeromedicalCenterName; }
			set { __AeromedicalCenterName = value; }
		}

		public AeromedicalCenter()
		{
		}
	}
}
