//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4048
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4048";
	}




	[XmlType(TypeName="ASCertificateType",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class ASCertificateType
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="ASCertificateTypeCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __ASCertificateTypeCode;
		
		[XmlIgnore]
		public string ASCertificateTypeCode
		{ 
			get { return __ASCertificateTypeCode; }
			set { __ASCertificateTypeCode = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="ASCertificateTypeName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __ASCertificateTypeName;
		
		[XmlIgnore]
		public string ASCertificateTypeName
		{ 
			get { return __ASCertificateTypeName; }
			set { __ASCertificateTypeName = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="ASCertificateTypeNameAlt",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __ASCertificateTypeNameAlt;
		
		[XmlIgnore]
		public string ASCertificateTypeNameAlt
		{ 
			get { return __ASCertificateTypeNameAlt; }
			set { __ASCertificateTypeNameAlt = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4000.GroupLicenseDependingRequirementsFiling),ElementName="GroupLicenseDependingRequirementsFiling",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4000.GroupLicenseDependingRequirementsFiling __GroupLicenseDependingRequirementsFiling;
		
		[XmlIgnore]
		public R_4000.GroupLicenseDependingRequirementsFiling GroupLicenseDependingRequirementsFiling
		{
			get {return __GroupLicenseDependingRequirementsFiling;}
			set {__GroupLicenseDependingRequirementsFiling = value;}
		}

		public ASCertificateType()
		{
		}
	}
}
