//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4118
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4118";
	}




	[XmlType(TypeName="RTTrainingData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class RTTrainingData
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4104.ASCourseExam),ElementName="ASCourseExam",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4104.ASCourseExam __ASCourseExam;
		
		[XmlIgnore]
		public R_4104.ASCourseExam ASCourseExam
		{
			get {return __ASCourseExam;}
			set {__ASCourseExam = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4112.ASCoursePeriod),ElementName="ASCoursePeriod",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4112.ASCoursePeriod __ASCoursePeriod;
		
		[XmlIgnore]
		public R_4112.ASCoursePeriod ASCoursePeriod
		{
			get {return __ASCoursePeriod;}
			set {__ASCoursePeriod = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="ASRTCourseHours",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __ASRTCourseHours;
		
		[XmlIgnore]
		public string ASRTCourseHours
		{ 
			get { return __ASRTCourseHours; }
			set { __ASRTCourseHours = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4110.ATO),ElementName="ATO",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4110.ATO __ATO;
		
		[XmlIgnore]
		public R_4110.ATO ATO
		{
			get {return __ATO;}
			set {__ATO = value;}
		}

		public RTTrainingData()
		{
		}
	}
}
