//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4168
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4168";
	}




	[XmlType(TypeName="FlightSkillTest",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class FlightSkillTest
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="FlightSkillTestCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FlightSkillTestCode;
		
		[XmlIgnore]
		public string FlightSkillTestCode
		{ 
			get { return __FlightSkillTestCode; }
			set { __FlightSkillTestCode = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="FlightSkillTestName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FlightSkillTestName;
		
		[XmlIgnore]
		public string FlightSkillTestName
		{ 
			get { return __FlightSkillTestName; }
			set { __FlightSkillTestName = value; }
		}

		public FlightSkillTest()
		{
		}
	}
}
