//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4238
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4238";
	}




	[XmlType(TypeName="RecognitionCreditsMaintenanceTrainingAircraft",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class RecognitionCreditsMaintenanceTrainingAircraft
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="DescriptionClaimedCreditRecognitionMaintenanceTrainingAircraft",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string DescriptionClaimedCreditRecognitionMaintenanceTrainingAircraft { get; set; }

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="DescriptionClaimedCreditExperienceTrainingMaintenanceAircraft",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string DescriptionClaimedCreditExperienceTrainingMaintenanceAircraft { get; set; }

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="DescriptionClaimedCreditEquivalentExamsGraduationMaintenanceAircraft",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string DescriptionClaimedCreditEquivalentExamsGraduationMaintenanceAircraft { get; set; }

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="CreditingPracticalExperienceGainedTrainingSection",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="boolean",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool CreditingPracticalExperienceGainedTrainingSection { get; set; }

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="CreditEquivalentExamsGraduation",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="boolean",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool CreditEquivalentExamsGraduation { get; set; }

		public RecognitionCreditsMaintenanceTrainingAircraft()
		{
		}
	}
}
