//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4268
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4268";
	}




	[XmlType(TypeName="CoordinationActivitiesInteractionAirTrafficManagementPermission",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class CoordinationActivitiesInteractionAirTrafficManagementPermission
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="CoordinationActivitiesInteractionAirTrafficManagementPermissionCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string CoordinationActivitiesInteractionAirTrafficManagementPermissionCode { get; set; }

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="CoordinationActivitiesInteractionAirTrafficManagementPermissionName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string CoordinationActivitiesInteractionAirTrafficManagementPermissionName { get; set; }

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="CoordinationActivitiesInteractionAirTrafficManagementPermissionNameEnglish",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string CoordinationActivitiesInteractionAirTrafficManagementPermissionNameEnglish { get; set; }

		public CoordinationActivitiesInteractionAirTrafficManagementPermission()
		{
		}
	}
}
