//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4226
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4226";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class AircraftDescriptionCollection : System.Collections.Generic.List<AircraftDescription>
	{
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class AircraftMaintenanceCategoryLicenseCollection : System.Collections.Generic.List<R_4224.AircraftMaintenanceCategoryLicense>
	{
	}



	[XmlType(TypeName="AircraftMaintenanceCategoryLicenseCandidatesApplicant",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class AircraftMaintenanceCategoryLicenseCandidatesApplicant
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4224.AircraftMaintenanceCategoryLicense),ElementName="AircraftMaintenanceCategoryLicense",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public AircraftMaintenanceCategoryLicenseCollection __AircraftMaintenanceCategoryLicenseCollection;
		
		[XmlIgnore]
		public AircraftMaintenanceCategoryLicenseCollection AircraftMaintenanceCategoryLicenseCollection
		{
			get
			{
				if (__AircraftMaintenanceCategoryLicenseCollection == null) __AircraftMaintenanceCategoryLicenseCollection = new AircraftMaintenanceCategoryLicenseCollection();
				return __AircraftMaintenanceCategoryLicenseCollection;
			}
			set {__AircraftMaintenanceCategoryLicenseCollection = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(AircraftDescription),ElementName="AircraftDescription",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public AircraftDescriptionCollection __AircraftDescriptionCollection;
		
		[XmlIgnore]
		public AircraftDescriptionCollection AircraftDescriptionCollection
		{
			get
			{
				if (__AircraftDescriptionCollection == null) __AircraftDescriptionCollection = new AircraftDescriptionCollection();
				return __AircraftDescriptionCollection;
			}
			set {__AircraftDescriptionCollection = value;}
		}

		public AircraftMaintenanceCategoryLicenseCandidatesApplicant()
		{
		}
	}


	[XmlType(TypeName="AircraftDescription",Namespace=Declarations.SchemaVersion),Serializable]
	public partial class AircraftDescription
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4224.AircraftMaintenanceCategoryLicense),ElementName="AircraftMaintenanceCategoryLicense",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4224.AircraftMaintenanceCategoryLicense __AircraftMaintenanceCategoryLicense;
		
		[XmlIgnore]
		public R_4224.AircraftMaintenanceCategoryLicense AircraftMaintenanceCategoryLicense
		{
			get {return __AircraftMaintenanceCategoryLicense;}
			set {__AircraftMaintenanceCategoryLicense = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4152.AircraftClass),ElementName="AircraftClass",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4152.AircraftClass __AircraftClass;
		
		[XmlIgnore]
		public R_4152.AircraftClass AircraftClass
		{
			get {return __AircraftClass;}
			set {__AircraftClass = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4158.AircraftType),ElementName="AircraftType",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4158.AircraftType __AircraftType;
		
		[XmlIgnore]
		public R_4158.AircraftType AircraftType
		{
			get {return __AircraftType;}
			set {__AircraftType = value;}
		}

		public AircraftDescription()
		{
		}
	}
}
