//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4282
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4282";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class OVDQualificationClassPermissionCollection : System.Collections.Generic.List<R_4260.OVDQualificationClassPermission>
	{
	}



	[XmlType(TypeName="OVDQualificationClassData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class OVDQualificationClassData
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4252.OVDQualificationClass),ElementName="OVDQualificationClass",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4252.OVDQualificationClass OVDQualificationClass { get; set; }

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4274.OVDBodyLocationIndicator),ElementName="OVDBodyLocationIndicator",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4274.OVDBodyLocationIndicator OVDBodyLocationIndicator { get; set; }

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4280.SectorWorkplaceAviationGroundStaff),ElementName="SectorWorkplaceAviationGroundStaff",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4280.SectorWorkplaceAviationGroundStaff SectorWorkplaceAviationGroundStaff { get; set; }

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4260.OVDQualificationClassPermission),ElementName="OVDQualificationClassPermission",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public OVDQualificationClassPermissionCollection OVDQualificationClassPermissionCollection { get; set; }

		public OVDQualificationClassData()
		{
		}
	}
}
