//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4392
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4392";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class ProvidingDocumentCollection : System.Collections.Generic.List<R_4388.ProvidingDocument>
	{
	}



	[XmlType(TypeName="SubmissionTerms",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class SubmissionTerms
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="ProvidingDocumentName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __ProvidingDocumentName;
		
		[XmlIgnore]
		public string ProvidingDocumentName
		{ 
			get { return __ProvidingDocumentName; }
			set { __ProvidingDocumentName = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4388.ProvidingDocument),ElementName="ProvidingDocument",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ProvidingDocumentCollection __ProvidingDocumentCollection;
		
		[XmlIgnore]
		public ProvidingDocumentCollection ProvidingDocumentCollection
		{
			get
			{
				if (__ProvidingDocumentCollection == null) __ProvidingDocumentCollection = new ProvidingDocumentCollection();
				return __ProvidingDocumentCollection;
			}
			set {__ProvidingDocumentCollection = value;}
		}

		public SubmissionTerms()
		{
		}
	}
}
