//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4400
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4400";
	}




	[XmlType(TypeName="AircraftData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class AircraftData
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_3988.ManufacturerContactData),ElementName="ManufacturerContactData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_3988.ManufacturerContactData __ManufacturerContactData;
		
		[XmlIgnore]
		public R_3988.ManufacturerContactData ManufacturerContactData
		{
			get {return __ManufacturerContactData;}
			set {__ManufacturerContactData = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4322.AircraftManufacturerCountry),ElementName="AircraftManufacturerCountry",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4322.AircraftManufacturerCountry __AircraftManufacturerCountry;
		
		[XmlIgnore]
		public R_4322.AircraftManufacturerCountry AircraftManufacturerCountry
		{
			get {return __AircraftManufacturerCountry;}
			set {__AircraftManufacturerCountry = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="AircraftManufacturePlace",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __AircraftManufacturePlace;
		
		[XmlIgnore]
		public string AircraftManufacturePlace
		{ 
			get { return __AircraftManufacturePlace; }
			set { __AircraftManufacturePlace = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="AircraftManufactureDate",Form=XmlSchemaForm.Qualified,DataType="date",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DateTime? __AircraftManufactureDate;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __AircraftManufactureDateSpecified { get { return __AircraftManufactureDate.HasValue; } }
		
		[XmlIgnore]
		public DateTime? AircraftManufactureDate
		{ 
			get { return __AircraftManufactureDate; }
			set { __AircraftManufactureDate = value; }
		}
		


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4158.AircraftType),ElementName="AircraftType",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4158.AircraftType __AircraftType;
		
		[XmlIgnore]
		public R_4158.AircraftType AircraftType
		{
			get {return __AircraftType;}
			set {__AircraftType = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="AircraftSeries",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __AircraftSeries;
		
		[XmlIgnore]
		public string AircraftSeries
		{ 
			get { return __AircraftSeries; }
			set { __AircraftSeries = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="AircraftSerialNumber",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __AircraftSerialNumber;
		
		[XmlIgnore]
		public string AircraftSerialNumber
		{ 
			get { return __AircraftSerialNumber; }
			set { __AircraftSerialNumber = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="AircraftUnused",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="boolean",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __AircraftUnused;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __AircraftUnusedSpecified;
		
		[XmlIgnore]
		public bool AircraftUnused
		{ 
			get { return __AircraftUnused; }
			set { __AircraftUnused = value; __AircraftUnusedSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4324.CountryLastRegistration),ElementName="CountryLastRegistration",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4324.CountryLastRegistration __CountryLastRegistration;
		
		[XmlIgnore]
		public R_4324.CountryLastRegistration CountryLastRegistration
		{
			get {return __CountryLastRegistration;}
			set {__CountryLastRegistration = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4318.AircraftOperationType),ElementName="AircraftOperationType",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4318.AircraftOperationType __AircraftOperationType;
		
		[XmlIgnore]
		public R_4318.AircraftOperationType AircraftOperationType
		{
			get {return __AircraftOperationType;}
			set {__AircraftOperationType = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="AircraftMaximumTakeOffWeight",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="integer",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __AircraftMaximumTakeOffWeight;
		
		[XmlIgnore]
		public string AircraftMaximumTakeOffWeight
		{ 
			get { return __AircraftMaximumTakeOffWeight; }
			set { __AircraftMaximumTakeOffWeight = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="CurrentAircraftRegistrationMark",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __CurrentAircraftRegistrationMark;
		
		[XmlIgnore]
		public string CurrentAircraftRegistrationMark
		{ 
			get { return __CurrentAircraftRegistrationMark; }
			set { __CurrentAircraftRegistrationMark = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="DesiredAircraftRegistrationMark",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __DesiredAircraftRegistrationMark;
		
		[XmlIgnore]
		public string DesiredAircraftRegistrationMark
		{ 
			get { return __DesiredAircraftRegistrationMark; }
			set { __DesiredAircraftRegistrationMark = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="AircraftStandardsCertified",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __AircraftStandardsCertified;
		
		[XmlIgnore]
		public string AircraftStandardsCertified
		{ 
			get { return __AircraftStandardsCertified; }
			set { __AircraftStandardsCertified = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="FlightCertificateNumber",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FlightCertificateNumber;
		
		[XmlIgnore]
		public string FlightCertificateNumber
		{ 
			get { return __FlightCertificateNumber; }
			set { __FlightCertificateNumber = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="FlightCertificateCertificationTableNumber",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FlightCertificateCertificationTableNumber;
		
		[XmlIgnore]
		public string FlightCertificateCertificationTableNumber
		{ 
			get { return __FlightCertificateCertificationTableNumber; }
			set { __FlightCertificateCertificationTableNumber = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="SeatsCount",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="integer",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __SeatsCount;
		
		[XmlIgnore]
		public string SeatsCount
		{ 
			get { return __SeatsCount; }
			set { __SeatsCount = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4326.FlightCertificateCountryIssuer),ElementName="FlightCertificateCountryIssuer",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4326.FlightCertificateCountryIssuer __FlightCertificateCountryIssuer;
		
		[XmlIgnore]
		public R_4326.FlightCertificateCountryIssuer FlightCertificateCountryIssuer
		{
			get {return __FlightCertificateCountryIssuer;}
			set {__FlightCertificateCountryIssuer = value;}
		}

		public AircraftData()
		{
		}
	}
}
