//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4468
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4468";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class AttachedDocumentDataGVAWithWhenAppliedCollection : System.Collections.Generic.List<R_4462.AttachedDocumentDataGVAWithWhenApplied>
	{
	}



	[XmlType(TypeName="AttachedDocumentDatasGVAWithWhenAppliedCollection",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class AttachedDocumentDatasGVAWithWhenAppliedCollection
	{


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4462.AttachedDocumentDataGVAWithWhenApplied),ElementName="AttachedDocumentDataGVAWithWhenApplied",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public AttachedDocumentDataGVAWithWhenAppliedCollection AttachedDocumentDataGVAWithWhenAppliedCollection { get; set; }

		public AttachedDocumentDatasGVAWithWhenAppliedCollection()
		{
		}
	}
}
