//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4584
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4584";
	}




	[XmlType(TypeName="ContactInformation",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class ContactInformation
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4286.CorrespondenceAddress),ElementName="CorrespondenceAddress",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4286.CorrespondenceAddress __CorrespondenceAddress;
		
		[XmlIgnore]
		public R_4286.CorrespondenceAddress CorrespondenceAddress
		{
			get {return __CorrespondenceAddress;}
			set {__CorrespondenceAddress = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4288.CorrespondenceAddressAbroad),ElementName="CorrespondenceAddressAbroad",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4288.CorrespondenceAddressAbroad __CorrespondenceAddressAbroad;
		
		[XmlIgnore]
		public R_4288.CorrespondenceAddressAbroad CorrespondenceAddressAbroad
		{
			get {return __CorrespondenceAddressAbroad;}
			set {__CorrespondenceAddressAbroad = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="PhoneNumbersDesc",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __PhoneNumbersDesc;
		
		[XmlIgnore]
		public string PhoneNumbersDesc
		{ 
			get { return __PhoneNumbersDesc; }
			set { __PhoneNumbersDesc = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="FaxNumbersDesc",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FaxNumbersDesc;
		
		[XmlIgnore]
		public string FaxNumbersDesc
		{ 
			get { return __FaxNumbersDesc; }
			set { __FaxNumbersDesc = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="EmailAddress",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __EmailAddress;
		
		[XmlIgnore]
		public string EmailAddress
		{ 
			get { return __EmailAddress; }
			set { __EmailAddress = value; }
		}

		public ContactInformation()
		{
		}
	}
}
