//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4574
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4574";
	}




	[XmlType(TypeName="AmateurAircraftProductionData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class AmateurAircraftProductionData
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_3988.ManufacturerContactData),ElementName="ManufacturerContactData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_3988.ManufacturerContactData __ManufacturerContactData;
		
		[XmlIgnore]
		public R_3988.ManufacturerContactData ManufacturerContactData
		{
			get {return __ManufacturerContactData;}
			set {__ManufacturerContactData = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4572.CategoryELVS),ElementName="CategoryELVS",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4572.CategoryELVS __CategoryELVS;
		
		[XmlIgnore]
		public R_4572.CategoryELVS CategoryELVS
		{
			get {return __CategoryELVS;}
			set {__CategoryELVS = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="AircraftMaximumTakeOffWeight",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="integer",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __AircraftMaximumTakeOffWeight;
		
		[XmlIgnore]
		public string AircraftMaximumTakeOffWeight
		{ 
			get { return __AircraftMaximumTakeOffWeight; }
			set { __AircraftMaximumTakeOffWeight = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="AircraftRegistrationMark",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __AircraftRegistrationMark;
		
		[XmlIgnore]
		public string AircraftRegistrationMark
		{ 
			get { return __AircraftRegistrationMark; }
			set { __AircraftRegistrationMark = value; }
		}

		public AmateurAircraftProductionData()
		{
		}
	}
}
