//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4504
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4504";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class EngineTTSNCollection : System.Collections.Generic.List<EngineTTSN>
	{
	}



	[XmlType(TypeName="EnginesTTSN",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class EnginesTTSN
	{


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(EngineTTSN),ElementName="EngineTTSN",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public EngineTTSNCollection EngineTTSNCollection { get; set; }

		public EnginesTTSN()
		{
		}
	}


	[XmlType(TypeName="EngineTTSN",Namespace=Declarations.SchemaVersion),Serializable]
	public partial class EngineTTSN
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="EngineTTSNHours",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string EngineTTSNHours { get; set; }

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="EngineTTSNLandingsCount",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string EngineTTSNLandingsCount { get; set; }

		public EngineTTSN()
		{
		}
	}
}
