//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4638
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4638";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class ShareholderOwnerCollection : System.Collections.Generic.List<R_4636.ShareholderOwner>
	{
	}



	[XmlType(TypeName="ShareholdersOwnersCollection",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class ShareholdersOwnersCollection
	{


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4636.ShareholderOwner),ElementName="ShareholderOwner",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ShareholderOwnerCollection __ShareholderOwnerCollection;
		
		[XmlIgnore]
		public ShareholderOwnerCollection ShareholderOwnerCollection
		{
			get
			{
				if (__ShareholderOwnerCollection == null) __ShareholderOwnerCollection = new ShareholderOwnerCollection();
				return __ShareholderOwnerCollection;
			}
			set {__ShareholderOwnerCollection = value;}
		}

		public ShareholdersOwnersCollection()
		{
		}
	}
}
