//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4736
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4736";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class DerogationCollection : System.Collections.Generic.List<R_4734.Derogation>
	{
	}



	[XmlType(TypeName="DerogationWithSubcategories",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class DerogationWithSubcategories
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4734.Derogation),ElementName="Derogation",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4734.Derogation __Derogation;
		
		[XmlIgnore]
		public R_4734.Derogation Derogation
		{
			get {return __Derogation;}
			set {__Derogation = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4734.Derogation),ElementName="DerogationCategories",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DerogationCollection __DerogationCategoriesCollection;
		
		[XmlIgnore]
		public DerogationCollection DerogationCategoriesCollection
		{
			get
			{
				if (__DerogationCategoriesCollection == null) __DerogationCategoriesCollection = new DerogationCollection();
				return __DerogationCategoriesCollection;
			}
			set {__DerogationCategoriesCollection = value;}
		}

		public DerogationWithSubcategories()
		{
		}
	}
}
