//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4746
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4746";
	}




	[XmlType(TypeName="FacilityKind",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class FacilityKind
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="FacilityKindCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FacilityKindCode;
		
		[XmlIgnore]
		public string FacilityKindCode
		{ 
			get { return __FacilityKindCode; }
			set { __FacilityKindCode = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="FacilityKindName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FacilityKindName;
		
		[XmlIgnore]
		public string FacilityKindName
		{ 
			get { return __FacilityKindName; }
			set { __FacilityKindName = value; }
		}

		public FacilityKind()
		{
		}
	}
}
