//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4830
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4830";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class CourseCollection : System.Collections.Generic.List<R_4816.Course>
	{
	}



	[XmlType(TypeName="TeacherInstructor",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class TeacherInstructor
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="TeachersInstructorsNames",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __TeachersInstructorsNames;
		
		[XmlIgnore]
		public string TeachersInstructorsNames
		{ 
			get { return __TeachersInstructorsNames; }
			set { __TeachersInstructorsNames = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="TeachersInstructorsCertificateNumber",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __TeachersInstructorsCertificateNumber;
		
		[XmlIgnore]
		public string TeachersInstructorsCertificateNumber
		{ 
			get { return __TeachersInstructorsCertificateNumber; }
			set { __TeachersInstructorsCertificateNumber = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4816.Course),ElementName="Course",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CourseCollection __CourseCollection;
		
		[XmlIgnore]
		public CourseCollection CourseCollection
		{
			get
			{
				if (__CourseCollection == null) __CourseCollection = new CourseCollection();
				return __CourseCollection;
			}
			set {__CourseCollection = value;}
		}

		public TeacherInstructor()
		{
		}
	}
}
