//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4872
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4872";
	}




	[XmlType(TypeName="FSTDType",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class FSTDType
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="FSTDTypeCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FSTDTypeCode;
		
		[XmlIgnore]
		public string FSTDTypeCode
		{ 
			get { return __FSTDTypeCode; }
			set { __FSTDTypeCode = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="FSTDTypeName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FSTDTypeName;
		
		[XmlIgnore]
		public string FSTDTypeName
		{ 
			get { return __FSTDTypeName; }
			set { __FSTDTypeName = value; }
		}

		public FSTDType()
		{
		}
	}
}
