//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_4888
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-4888";
	}




	[XmlType(TypeName="FSTDDetails",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class FSTDDetails
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4158.AircraftType),ElementName="AircraftType",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4158.AircraftType __AircraftType;
		
		[XmlIgnore]
		public R_4158.AircraftType AircraftType
		{
			get {return __AircraftType;}
			set {__AircraftType = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4872.FSTDType),ElementName="FSTDType",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4872.FSTDType __FSTDType;
		
		[XmlIgnore]
		public R_4872.FSTDType FSTDType
		{
			get {return __FSTDType;}
			set {__FSTDType = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="FSTDLocation",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FSTDLocation;
		
		[XmlIgnore]
		public string FSTDLocation
		{ 
			get { return __FSTDLocation; }
			set { __FSTDLocation = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="FSTDQualificationLevel",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FSTDQualificationLevel;
		
		[XmlIgnore]
		public string FSTDQualificationLevel
		{ 
			get { return __FSTDQualificationLevel; }
			set { __FSTDQualificationLevel = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="FSTDIdCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FSTDIdCode;
		
		[XmlIgnore]
		public string FSTDIdCode
		{ 
			get { return __FSTDIdCode; }
			set { __FSTDIdCode = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="FSTDSerialNumber",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FSTDSerialNumber;
		
		[XmlIgnore]
		public string FSTDSerialNumber
		{ 
			get { return __FSTDSerialNumber; }
			set { __FSTDSerialNumber = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="ManufacturerName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __ManufacturerName;
		
		[XmlIgnore]
		public string ManufacturerName
		{ 
			get { return __ManufacturerName; }
			set { __ManufacturerName = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="CountryGRAOCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __CountryGRAOCode;
		
		[XmlIgnore]
		public string CountryGRAOCode
		{ 
			get { return __CountryGRAOCode; }
			set { __CountryGRAOCode = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="CountryName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __CountryName;
		
		[XmlIgnore]
		public string CountryName
		{ 
			get { return __CountryName; }
			set { __CountryName = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="ManufacturingDate",Form=XmlSchemaForm.Qualified,DataType="date",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DateTime? __ManufacturingDate;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __ManufacturingDateSpecified { get { return __ManufacturingDate.HasValue; } }
		
		[XmlIgnore]
		public DateTime? ManufacturingDate
		{ 
			get { return __ManufacturingDate; }
			set { __ManufacturingDate = value; }
		}
		


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4412.EngineType),ElementName="EngineTypeA",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4412.EngineType __EngineTypeA;
		
		[XmlIgnore]
		public R_4412.EngineType EngineTypeA
		{
			get {return __EngineTypeA;}
			set {__EngineTypeA = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4412.EngineType),ElementName="EngineTypeB",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4412.EngineType __EngineTypeB;
		
		[XmlIgnore]
		public R_4412.EngineType EngineTypeB
		{
			get {return __EngineTypeB;}
			set {__EngineTypeB = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="FSTDVisualSystem",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FSTDVisualSystem;
		
		[XmlIgnore]
		public string FSTDVisualSystem
		{ 
			get { return __FSTDVisualSystem; }
			set { __FSTDVisualSystem = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="FSTDMotionSystem",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FSTDMotionSystem;
		
		[XmlIgnore]
		public string FSTDMotionSystem
		{ 
			get { return __FSTDMotionSystem; }
			set { __FSTDMotionSystem = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="Location",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Location;
		
		[XmlIgnore]
		public string Location
		{ 
			get { return __Location; }
			set { __Location = value; }
		}

		public FSTDDetails()
		{
		}
	}
}
