//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_5064
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-5064";
	}




	[XmlType(TypeName="SpecialRestriction",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class SpecialRestriction
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="SpecialRestrictionCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __SpecialRestrictionCode;
		
		[XmlIgnore]
		public string SpecialRestrictionCode
		{ 
			get { return __SpecialRestrictionCode; }
			set { __SpecialRestrictionCode = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="SpecialRestrictionName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __SpecialRestrictionName;
		
		[XmlIgnore]
		public string SpecialRestrictionName
		{ 
			get { return __SpecialRestrictionName; }
			set { __SpecialRestrictionName = value; }
		}

		public SpecialRestriction()
		{
		}
	}
}
