//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_5034
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-5034";
	}




	[XmlType(TypeName="DataCommercialTransportAircraft",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class DataCommercialTransportAircraft
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4322.AircraftManufacturerCountry),ElementName="AircraftManufacturerCountry",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4322.AircraftManufacturerCountry __AircraftManufacturerCountry;
		
		[XmlIgnore]
		public R_4322.AircraftManufacturerCountry AircraftManufacturerCountry
		{
			get {return __AircraftManufacturerCountry;}
			set {__AircraftManufacturerCountry = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="AircraftRegistrationMark",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __AircraftRegistrationMark;
		
		[XmlIgnore]
		public string AircraftRegistrationMark
		{ 
			get { return __AircraftRegistrationMark; }
			set { __AircraftRegistrationMark = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_4158.AircraftType),ElementName="AircraftType",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_4158.AircraftType __AircraftType;
		
		[XmlIgnore]
		public R_4158.AircraftType AircraftType
		{
			get {return __AircraftType;}
			set {__AircraftType = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="AircraftSeries",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __AircraftSeries;
		
		[XmlIgnore]
		public string AircraftSeries
		{ 
			get { return __AircraftSeries; }
			set { __AircraftSeries = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="ManufacturerName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __ManufacturerName;
		
		[XmlIgnore]
		public string ManufacturerName
		{ 
			get { return __ManufacturerName; }
			set { __ManufacturerName = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_5030.AircraftModel),ElementName="AircraftModel",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_5030.AircraftModel __AircraftModel;
		
		[XmlIgnore]
		public R_5030.AircraftModel AircraftModel
		{
			get {return __AircraftModel;}
			set {__AircraftModel = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="AircraftSerialNumber",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __AircraftSerialNumber;
		
		[XmlIgnore]
		public string AircraftSerialNumber
		{ 
			get { return __AircraftSerialNumber; }
			set { __AircraftSerialNumber = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="SeatsCount",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="integer",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __SeatsCount;
		
		[XmlIgnore]
		public string SeatsCount
		{ 
			get { return __SeatsCount; }
			set { __SeatsCount = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="AircraftMaximumTakeOffWeight",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="integer",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __AircraftMaximumTakeOffWeight;
		
		[XmlIgnore]
		public string AircraftMaximumTakeOffWeight
		{ 
			get { return __AircraftMaximumTakeOffWeight; }
			set { __AircraftMaximumTakeOffWeight = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="BaseAircraft",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __BaseAircraft;
		
		[XmlIgnore]
		public string BaseAircraft
		{ 
			get { return __BaseAircraft; }
			set { __BaseAircraft = value; }
		}

		public DataCommercialTransportAircraft()
		{
		}
	}
}
