//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_5158
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-5158";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class AircraftClassTypeFSTDCollection : System.Collections.Generic.List<R_5156.AircraftClassTypeFSTD>
	{
	}



	[XmlType(TypeName="AircraftClassTypeFSTDsCollection",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class AircraftClassTypeFSTDsCollection
	{


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_5156.AircraftClassTypeFSTD),ElementName="AircraftClassTypeFSTD",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public AircraftClassTypeFSTDCollection AircraftClassTypeFSTDCollection { get; set; }

		public AircraftClassTypeFSTDsCollection()
		{
		}
	}
}
