//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_6052
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-6052";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class AttachedDocumentDescriptionIdentifierCollection : System.Collections.Generic.List<R_6050.AttachedDocumentDescriptionIdentifier>
	{
	}



	[XmlType(TypeName="AttachedDocumentDescriptionIdentifiersCollection",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class AttachedDocumentDescriptionIdentifiersCollection
	{


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(Type=typeof(R_6050.AttachedDocumentDescriptionIdentifier),ElementName="AttachedDocumentDescriptionIdentifier",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public AttachedDocumentDescriptionIdentifierCollection __AttachedDocumentDescriptionIdentifierCollection;
		
		[XmlIgnore]
		public AttachedDocumentDescriptionIdentifierCollection AttachedDocumentDescriptionIdentifierCollection
		{
			get
			{
				if (__AttachedDocumentDescriptionIdentifierCollection == null) __AttachedDocumentDescriptionIdentifierCollection = new AttachedDocumentDescriptionIdentifierCollection();
				return __AttachedDocumentDescriptionIdentifierCollection;
			}
			set {__AttachedDocumentDescriptionIdentifierCollection = value;}
		}

		public AttachedDocumentDescriptionIdentifiersCollection()
		{
		}
	}
}
