//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_7014
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-7014";
	}

	[Serializable]
	public enum ModificationTypeNomenclature
	{
		[XmlEnum(Name="Empty")] Empty,
		[XmlEnum(Name="Create")] Create,
		[XmlEnum(Name="Update")] Update,
		[XmlEnum(Name="Delete")] Delete
	}




	[XmlType(TypeName="OrganizationalFormLNPE",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class OrganizationalFormLNPE
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="modificationType")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_7066.ModificationTypeNomenclature modificationType { get; set; }

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="OrganizationalFormLNPECode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string OrganizationalFormLNPECode { get; set; }

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlElement(ElementName="OrganizationalFormLNPEName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string OrganizationalFormLNPEName { get; set; }

		public OrganizationalFormLNPE()
		{
		}
	}
}
