//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_7066
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/nomenclature/R-7066";
	}

	[Serializable]
	public enum ModificationTypeNomenclature
	{
		[XmlEnum(Name="Empty")] Empty,
		[XmlEnum(Name="Create")] Create,
		[XmlEnum(Name="Update")] Update,
		[XmlEnum(Name="Delete")] Delete
	}


}
