PRINT 'caa'
GO

INSERT INTO Noms (NomId, Name, Alias) VALUES (37,N'Въздухоплавателни администрации',N'caa');
GO

SET IDENTITY_INSERT [NomValues] ON
GO

INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7844,37,N'CAD SRB',N'Civil Aviation Directorate of the Republic of Serbia',N'Civil Aviation Directorate of the Republic of Serbia',67,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7845,37,N'DGCA',N'DGCA ',N'DGCA - Sri lanka',9,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7846,37,N'RU',N'Федерална агенция за въздушен траспорт',N'Federal Agency Aviation Transport',18,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7847,37,N'CAAC',N'Гражданска въздухоплавателна администрация Китай',N'Civil Aviation Administration of China',11,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7848,37,N'MNE',N'Civil Aviation Agency-Montenegro',N'Civil Aviation Agency-Montenegro',12,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7849,37,N'LCAA',N'Lithuania Civil Aviation Administration',N'Lithuania Civil Aviation Administration',16,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7850,37,N'AL',N'DGCAA Albania',N'DGCAA Albania',21,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7851,37,N'A',N'Austria',N'Austria',26,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7852,37,N'B',N'Belgium',N'Belgium',27,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7853,37,N'BG',N'ГЛАВНА ДИРЕКЦИЯ ГРАЖДАНСКА ВЪЗДУХОПЛАВАТЕЛНА АДМИНИСТРАЦИЯ',N'DIRECTORATE GENERAL CIVIL AVIATION ADMINISTRATION',58,NULL,1,N'{"heading":"МИНИСТЕРСТВО НА ТРАНСПОРТА","headingAlt":"MINISTRY OF TRANSPORT","subHeading":"ГЛАВНА ДИРЕКЦИЯ ГРАЖДАНСКА ВЪЗДУХОПЛАВАТЕЛНА АДМИНИСТРАЦИЯ","subHeadingAlt":"DIRECTORATE GENERAL CIVIL AVIATION ADMINISTRATION\\n"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7854,37,N'CY',N'Cyprus',N'Cyprus',28,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7855,37,N'CZ',N'Czech Republic',N'Czech Republic',29,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7856,37,N'DK',N'Denmark',N'Denmark',30,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7857,37,N'EST',N'Estonia',N'Estonia',31,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7858,37,N'FIN',N'Finland',N'Finland',32,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7859,37,N'FYROM',N'Former Yugoslav Republic of Macedonia',N'Former Yugoslav Republic of Macedonia',33,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7860,37,N'F',N'France',N'France',34,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7861,37,N'D',N'Germany',N'Germany',35,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7862,37,N'GR',N'Greece',N'Greece',36,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7863,37,N'H',N'Hungary',N'Hungary',37,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7864,37,N'IS',N'Iceland',N'Iceland',38,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7865,37,N'IRL',N'Ireland',N'Ireland',39,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7866,37,N'I',N'Italy',N'Italy',40,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7867,37,N'LVA',N'Latvia',N'Latvia',41,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7868,37,N'L',N'Luxembourg',N'Luxembourg',42,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7869,37,N'M',N'Malta',N'Malta',43,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7870,37,N'MD',N'Moldova',N'Moldova',44,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7871,37,N'MC',N'Monaco',N'Monaco',45,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7872,37,N'NL',N'Netherlands',N'Netherlands',46,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7873,37,N'N',N'Norway',N'Norway',47,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7874,37,N'PL',N'Poland',N'Poland',48,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7875,37,N'P',N'Portugal',N'Portugal',49,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7876,37,N'R',N'Romania',N'Romania',50,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7877,37,N'SK',N'Slovak Republic',N'Slovak Republic',51,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7878,37,N'SLO',N'Slovenia',N'Slovenia',52,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7879,37,N'E',N'Spain',N'Spain',53,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7880,37,N'SE',N'Sweden',N'Sweden',54,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7881,37,N'CH',N'Switzerland',N'Switzerland',55,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7882,37,N'TR',N'Turkey',N'Turkey',56,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7883,37,N'UK',N'United Kingdom Civil Aviation Authority',N'United Kingdom Civil Aviation Authority',57,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7884,37,N'IR',N'I.R. of IRAN',N'I.R. of IRAN',59,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7885,37,N'FAA',N'FAA',N'FAA',23,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7886,37,N'CAAS',N'Civil aviation Authority of Singapore',N'Civil aviation Authority of Singapore',64,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7887,37,N'NAM',N'DCA NAMIBIA',N'DCA NAMIBIA',65,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7888,37,N'NCAA',N'NCAA of Brazil',N'NCAA of Brazil',60,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7889,37,N'DCA',N'Department of Civil Aviation, Myanmar',N'Department of Civil Aviation, Myanmar',66,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7890,37,N'CA',N'Canada',N'Canada',71,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7891,37,N'CAA',N'Eritrea''s Civil Aviation Authority',N'Eritrea''s Civil Aviation Authority',76,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7892,37,N'UKR',N'CAA of Ukraine',N'CAA of Ukraine',61,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7893,37,N'CAD',N'Civil Aviation Department',N'Civil Aviation Department',80,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7894,37,N'CAAV',N'Глажданска въздухоплавателна администрация Виетнам',N'Civil Aviation Administration Vietnam',82,NULL,1,N'{"heading":null,"headingAlt":null,"subHeading":null,"subHeadingAlt":null}');
GO

SET IDENTITY_INSERT [NomValues] OFF
GO
