PRINT 'countries'
GO

INSERT INTO Noms (NomId, Name, Alias) VALUES (2,N'Държави',N'countries');
GO

SET IDENTITY_INSERT [NomValues] ON
GO

INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(4,2,N'IN',N'India',N'India',NULL,NULL,1,N'{"NationalityCodeCA":"IN","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"IN"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(5,2,N'AR',N'Аржентина',N'Argentina',NULL,NULL,1,N'{"NationalityCodeCA":"AR","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"AR"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(6,2,N'AZ',N'Азербайджан',N'Azerbaijan',NULL,NULL,1,N'{"NationalityCodeCA":"AZ","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"AZ"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7,2,N'SD',N'Судан',N'Sudan',NULL,NULL,1,N'{"NationalityCodeCA":"SD","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"SD"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(8,2,N'MW',N'Малави',N'Malawi',NULL,NULL,1,N'{"NationalityCodeCA":"MW","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"MW"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(9,2,N'LK',N'Шри Ланка',N'Sri Lanka',NULL,NULL,1,N'{"NationalityCodeCA":"LK","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"LK"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(10,2,N'HR',N'Republic of Groatia',N'Republic of Groatia',NULL,NULL,1,N'{"NationalityCodeCA":"HR","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"HR"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(11,2,N'CN',N'Китайска Народна Република',N'People''s Republic of China',NULL,NULL,1,N'{"NationalityCodeCA":"CN","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"CN"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(12,2,N'ME',N'Черна Гора',N'Montenegro',NULL,NULL,1,N'{"NationalityCodeCA":"MNE","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"ME"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(13,2,N'UKR',N'Украйна',N'Ukraine',NULL,NULL,1,N'{"NationalityCodeCA":"UKR","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"UKR"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(14,2,N'KWI',N'Кувейт',N'Kuwait',NULL,NULL,1,N'{"NationalityCodeCA":"KWI","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"KWI"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(15,2,N'ISL',N'Исландия',N'Iceland',NULL,NULL,1,N'{"NationalityCodeCA":"ISL","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"ISL"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(16,2,N'LT',N'Република Литва',N'Republic of Lithuania',NULL,NULL,1,N'{"NationalityCodeCA":"LT","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"LT"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(17,2,N'ZA',N'Република Южна Африка',N'Republic of South Africa',NULL,NULL,1,N'{"NationalityCodeCA":"ZA","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"ZA"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(18,2,N'RU',N'Русия',N'Russian Federation',NULL,NULL,1,N'{"NationalityCodeCA":"RU","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"RU"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(19,2,N'UZ',N'Узбекистан',N'Uzbekistan',NULL,NULL,1,N'{"NationalityCodeCA":"UZ","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"38"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(20,2,N'CG',N'Congo',N'Congo',NULL,NULL,1,N'{"NationalityCodeCA":"CG","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"CG"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(21,2,N'AL',N'Albania',N'Albania',NULL,NULL,1,N'{"NationalityCodeCA":"AL","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"AL"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(22,2,N'IO',N'British',N'British',NULL,NULL,1,N'{"NationalityCodeCA":"IO","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"GB"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(23,2,N'US',N'USA',N'USA',NULL,NULL,1,N'{"NationalityCodeCA":"US","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"USA"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(24,2,N'28',N'Испания',N'Spain',NULL,NULL,1,N'{"NationalityCodeCA":"E","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"28"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(25,2,N'-',N'-',N'-',NULL,NULL,1,N'{"NationalityCodeCA":"-","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"-"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(26,2,N'AT',N'Austria',N'Austria',NULL,NULL,1,N'{"NationalityCodeCA":"AT","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"A"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(27,2,N'BE',N'Belgium',N'Belgium',NULL,NULL,1,N'{"NationalityCodeCA":"BE","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"B"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(28,2,N'CY',N'Cyprus',N'Cyprus',NULL,NULL,1,N'{"NationalityCodeCA":"CY","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"CY"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(29,2,N'CZ',N'Czech Republic',N'Czech Republic',NULL,NULL,1,N'{"NationalityCodeCA":"CZ","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"CZ"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(30,2,N'DK',N'Denmark',N'Denmark',NULL,NULL,1,N'{"NationalityCodeCA":"DK","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"DK"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(31,2,N'EE',N'Estonia',N'Estonia',NULL,NULL,1,N'{"NationalityCodeCA":"EE","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"EST"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(32,2,N'FIN',N'Finland',N'Finland',NULL,NULL,1,N'{"NationalityCodeCA":"FIN","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"FIN"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(33,2,N'FYROM',N'Former Yugoslav Republic of Macedonia',N'Former Yugoslav Republic of Macedonia',NULL,NULL,1,N'{"NationalityCodeCA":"FYROM","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"FYROM"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(34,2,N'FR',N'Р. Франция',N'R.of France',NULL,NULL,1,N'{"NationalityCodeCA":"FR","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"FR"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(35,2,N'DE',N'Germany',N'Germany',NULL,NULL,1,N'{"NationalityCodeCA":"DE","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"D"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(36,2,N'GR',N'Greece',N'Greece',NULL,NULL,1,N'{"NationalityCodeCA":"GR","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"GR"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(37,2,N'H',N'Hungary',N'Hungary',NULL,NULL,1,N'{"NationalityCodeCA":"H","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"H"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(38,2,N'IS',N'Iceland',N'Iceland',NULL,NULL,1,N'{"NationalityCodeCA":"IS","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"IS"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(39,2,N'IRL',N'Ireland',N'Ireland',NULL,NULL,1,N'{"NationalityCodeCA":"IRL","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"IRL"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(40,2,N'IT',N'Italy',N'Italy',NULL,NULL,1,N'{"NationalityCodeCA":"IT","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"I"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(41,2,N'LVA',N'Latvia',N'Latvia',NULL,NULL,1,N'{"NationalityCodeCA":"LVA","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"LVA"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(42,2,N'L',N'Luxembourg',N'Luxembourg',NULL,NULL,1,N'{"NationalityCodeCA":"L","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"L"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(43,2,N'M',N'Malta',N'Malta',NULL,NULL,1,N'{"NationalityCodeCA":"M","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"M"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(44,2,N'MD',N'Moldova',N'Moldova',NULL,NULL,1,N'{"NationalityCodeCA":"MD","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"MD"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(45,2,N'MC',N'Monaco',N'Monaco',NULL,NULL,1,N'{"NationalityCodeCA":"MC","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"MC"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(46,2,N'NL',N'Netherlands',N'Netherlands',NULL,NULL,1,N'{"NationalityCodeCA":"NL","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"NL"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(47,2,N'N',N'Norway',N'Norway',NULL,NULL,1,N'{"NationalityCodeCA":"N","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"N"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(48,2,N'PL',N'Poland',N'Poland',NULL,NULL,1,N'{"NationalityCodeCA":"PL","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"PL"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(49,2,N'P',N'Portugal',N'Portugal',NULL,NULL,1,N'{"NationalityCodeCA":"P","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"P"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(50,2,N'R',N'Romania',N'Romania',NULL,NULL,1,N'{"NationalityCodeCA":"R","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"R"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(51,2,N'SK',N'Slovak Republic',N'Slovak Republic',NULL,NULL,1,N'{"NationalityCodeCA":"SK","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"SK"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(52,2,N'SI',N'Slovenia',N'Slovenia',NULL,NULL,1,N'{"NationalityCodeCA":"SI","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"SLO"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(53,2,N'E',N'Spain',N'Spain',NULL,NULL,1,N'{"NationalityCodeCA":"E","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"E"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(54,2,N'SE',N'Sweden',N'Sweden',NULL,NULL,1,N'{"NationalityCodeCA":"SE","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"SE"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(55,2,N'CH',N'Switzerland',N'Switzerland',NULL,NULL,1,N'{"NationalityCodeCA":"CH","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"CH"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(56,2,N'TR',N'Turkey',N'Turkey',NULL,NULL,1,N'{"NationalityCodeCA":"TR","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"TR"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(57,2,N'GB',N'United Kingdom',N'United Kingdom',NULL,NULL,1,N'{"NationalityCodeCA":"GB","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"UK"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(58,2,N'BG',N'Република България',N'Republic of Bulgaria',NULL,NULL,1,N'{"NationalityCodeCA":"BGR","Heading":"РЕПУБЛИКА БЪЛГАРИЯ","HeadingAlt":"REPUBLIC OF BULGARIA","LicenceCodeCA":"BGR."}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(59,2,N'IR',N'I.R. of IRAN',N'I.R. of IRAN',NULL,NULL,1,N'{"NationalityCodeCA":"IR","Heading":"-","HeadingAlt":"-","LicenceCodeCA":"IR"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(60,2,N'Br',N'Brazil',N'Brazil',NULL,NULL,1,N'{"NationalityCodeCA":"Br","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"Br"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(61,2,N'UA',N'Украйна',N'Ukraine',NULL,NULL,1,N'{"NationalityCodeCA":"UKR","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"UKR"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(62,2,N'IQ',N'Ирак',N'Iraq',NULL,NULL,1,N'{"NationalityCodeCA":"IQ","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"IQ"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(63,2,N'LB',N'Ливан',N'Lebanon',NULL,NULL,1,N'{"NationalityCodeCA":"LB","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"LB"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(64,2,N'SG',N'Singapore',N'Singapore',NULL,NULL,1,N'{"NationalityCodeCA":"SG","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"SG"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(65,2,N'NAM',N'Намибия',N'Namibia',NULL,NULL,1,N'{"NationalityCodeCA":"NAM","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"NAM"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(66,2,N'MMR',N'Република Съюз Мианмар',N'Union of Myanmar',NULL,NULL,1,N'{"NationalityCodeCA":"MMR","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"MMR"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(67,2,N'SRB',N'Republic of Serbia',N'Republic of Serbia',NULL,NULL,1,N'{"NationalityCodeCA":"SRB","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"SRB"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(68,2,N'NZ',N'New Zealand',N'New Zealand',NULL,NULL,1,N'{"NationalityCodeCA":"NZ","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"NZ"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(69,2,N'BA',N'Босна и Херцеговина',N'Bosnia and Herzegovina',NULL,NULL,1,N'{"NationalityCodeCA":"BA","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"BA"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(70,2,N'BGR',N'Република България',N'Republic of Bulgaria',NULL,NULL,1,N'{"NationalityCodeCA":"BGR","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"BGR"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(71,2,N'CA',N'Канада',N'Canada',NULL,NULL,1,N'{"NationalityCodeCA":"CA","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"CA"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(72,2,N'AU',N'Australia',N'Australia',NULL,NULL,1,N'{"NationalityCodeCA":"AU","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"CA"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(73,2,N'IL',N'Occupied Palestine',N'Occupied Palestine',NULL,NULL,1,N'{"NationalityCodeCA":"IL","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"IL"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(74,2,N'CU',N'Куба',N'Cuba',NULL,NULL,1,N'{"NationalityCodeCA":"CU","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"CU"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(75,2,N'МК',N'Република Македония',N'Republic of Macedonia',NULL,NULL,1,N'{"NationalityCodeCA":"МК","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"МК"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(76,2,N'ER',N'Еритрея',N'Eritrea',NULL,NULL,1,N'{"NationalityCodeCA":"ER","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"ER"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(77,2,N'DXB',N'Дубай',N'Dubai',NULL,NULL,1,N'{"NationalityCodeCA":"DXB","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"DXB"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(78,2,N'KZ',N'Казахстан',N'Kazahstan',NULL,NULL,1,N'{"NationalityCodeCA":"KZ","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"KZ"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(79,2,N'GE',N'Грузия',N'Georgia',NULL,NULL,1,N'{"NationalityCodeCA":"GE","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"GE"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(80,2,N'MUS',N'Република Мавриция',N'Republic of Mautitius',NULL,NULL,1,N'{"NationalityCodeCA":"MUS","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"MUS"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(81,2,N'BY',N'Беларус',N'Belarus',NULL,NULL,1,N'{"NationalityCodeCA":"BY","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"BY"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(82,2,N'VN',N'Социалистическа Република Виетнам',N'Socialist Republic of Vietnam',NULL,NULL,1,N'{"NationalityCodeCA":"VN","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"VN"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(83,2,N'JO',N'Йордания',N'Jordan',NULL,NULL,1,N'{"NationalityCodeCA":"JO","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"JO"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(84,2,N'SA',N'Саудитска Арабия',N'Saudi Arabia',NULL,NULL,1,N'{"NationalityCodeCA":"SA","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"SA"}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(85,2,N'BKK',N'Тайланд',N'Thailand',NULL,NULL,1,N'{"NationalityCodeCA":"VTBD","Heading":null,"HeadingAlt":null,"LicenceCodeCA":"VTBD"}');
GO

SET IDENTITY_INSERT [NomValues] OFF
GO
