PRINT 'limitations66'
GO

INSERT INTO Noms (NomId, Name, Alias) VALUES (32,N'Ограничения (Part-66)',N'limitations66');
GO

SET IDENTITY_INSERT [NomValues] ON
GO

INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7630,32,N'22',N'Electrical systems',N'Electrical systems',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7631,32,N'23',N'Instruments (mechanical, electrical & oxygen) systems',N'Instruments (mechanical, electrical & oxygen) systems',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7632,32,N'24',N'Navigation systems',N'Navigation systems',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7633,32,N'25',N'Avionic systems & LRU',N'Avionic systems & LRU',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7634,32,N'26',N'Airframe & mechanical systems',N'Airframe & mechanical systems',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7635,32,N'32',N'32',N'32',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7636,32,N'6.11',N'Math',N'Math',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7637,32,N'7.7',N'7.7',N'7.7',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7638,32,N'3',N'3',N'3',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7639,32,N'3.10',N'3.10',N'3.10',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7640,32,N'3.11',N'3.11',N'3.11',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7641,32,N'3.13',N'3.13',N'3.13',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7642,32,N'33',N'33',N'33',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7643,32,N'3.14',N'3.14',N'3.14',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7644,32,N'3.15',N'3.15',N'3.15',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7645,32,N'3.16',N'3.16',N'3.16',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7646,32,N'3.18',N'3.18',N'3.18',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7647,32,N'3.5',N'3.5',N'3.5',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7648,32,N'3.6',N'3.6',N'3.6',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7649,32,N'3.7',N'3.7',N'3.7',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7650,32,N'3.8',N'3.8',N'3.8',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7651,32,N'3.9',N'3.9',N'3.9',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7652,32,N'4',N'4',N'4',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7653,32,N'4.2',N'4.2',N'4.2',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7654,32,N'4.3',N'4.3',N'4.3',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7655,32,N'5',N'5',N'5',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7656,32,N'5.1',N'5.1',N'5.1',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7657,32,N'5.11',N'5.11',N'5.11',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7658,32,N'5.12',N'5.12',N'5.12',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7659,32,N'5.13',N'5.13',N'5.13',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7660,32,N'5.15',N'5.15',N'5.15',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7661,32,N'5.4',N'5.4',N'5.4',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7662,32,N'6',N'6',N'6',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7663,32,N'6.10',N'6.10',N'6.10',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7664,32,N'6.4',N'6.4',N'6.4',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7665,32,N'6.7',N'6.7',N'6.7',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7666,32,N'7',N'7',N'7',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7667,32,N'7.13',N'7.13',N'7.13',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7668,32,N'7.16',N'7.16',N'7.16',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7669,32,N'7.17',N'7.17',N'7.17',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7670,32,N'7.18',N'7.18',N'7.18',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7671,32,N'7.19',N'7.19',N'7.19',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7672,32,N'7.2',N'7.2',N'7.2',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7673,32,N'7.20',N'7.20',N'7.20',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7674,32,N'7.4',N'7.4',N'7.4',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7675,32,N'7.6',N'7.6',N'7.6',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7676,32,N'7.8',N'7.8',N'7.8',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7677,32,N'8',N'8',N'8',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7678,32,N'8.2',N'8.2',N'8.2',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7679,32,N'11',N'11',N'11',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7680,32,N'11.12',N'11.12',N'11.12',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7681,32,N'11.14',N'11.14',N'11.14',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7682,32,N'11.17',N'11.17',N'11.17',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7683,32,N'11.7',N'11.7',N'11.7',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7684,32,N'11.8',N'11.8',N'11.8',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7685,32,N'12.10',N'12.10',N'12.10',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7686,32,N'12.2',N'12.2',N'12.2',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7687,32,N'12.4',N'12.4',N'12.4',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7688,32,N'13',N'13',N'13',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7689,32,N'14',N'14',N'14',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7690,32,N'15',N'15',N'15',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7691,32,N'15.10',N'15.10',N'15.10',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7692,32,N'15.11',N'15.11',N'15.11',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7693,32,N'15.17',N'15.17',N'15.17',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7694,32,N'15.18',N'15.18',N'15.18',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7695,32,N'15.20',N'15.20',N'15.20',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7696,32,N'15.9',N'15.9',N'15.9',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7697,32,N'17',N'17',N'17',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7698,32,N'17.4',N'17.4',N'17.4',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7699,32,N'17.6',N'17.6',N'17.6',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7700,32,N'34',N'34',N'34',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7701,32,N'8.3',N'8.3',N'8.3',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7702,32,N'8.4',N'8.4',N'8.4',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7703,32,N'7.1',N'7.1',N'7.1',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7704,32,N'7.15',N'7.15',N'7.15',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7705,32,N'7.9',N'7.9',N'7.9',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7706,32,N'7.10',N'7.10',N'7.10',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7707,32,N'7.11',N'7.11',N'7.11',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7708,32,N'7.12',N'7.12',N'7.12',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7709,32,N'7.14',N'7.14',N'7.14',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7710,32,N'6.6',N'6.6',N'6.6',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7711,32,N'6.1',N'6.1',N'6.1',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7712,32,N'6.3',N'6.3',N'6.3',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7713,32,N'6.8',N'6.8',N'6.8',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7714,32,N'6.5',N'6.5',N'6.5',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7715,32,N'5.6',N'5.6',N'5.6',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7716,32,N'5.14',N'5.14',N'5.14',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7717,32,N'5.10',N'5.10',N'5.10',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7718,32,N'5.2',N'5.2',N'5.2',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7719,32,N'5.3',N'5.3',N'5.3',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7720,32,N'3.1',N'3.1',N'3.1',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7721,32,N'3.17',N'3.17',N'3.17',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7722,32,N'3.12',N'3.12',N'3.12',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7723,32,N'3.4',N'3.4',N'3.4',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7724,32,N'16.10',N'16.10',N'16.10',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7725,32,N'16.7',N'16.7',N'16.7',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7726,32,N'15.14',N'15.14',N'15.14',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7727,32,N'15.5',N'15.5',N'15.5',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7728,32,N'15.13',N'15.13',N'15.13',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7729,32,N'13.1',N'13.1',N'13.1',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7730,32,N'13.9',N'13.9',N'13.9',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7731,32,N'13.4',N'13.4',N'13.4',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7732,32,N'13.10',N'13.10',N'13.10',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7733,32,N'13.6',N'13.6',N'13.6',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7734,32,N'13.7',N'13.7',N'13.7',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7735,32,N'12',N'12',N'12',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7736,32,N'12.1',N'12.1',N'12.1',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7737,32,N'12.3',N'12.3',N'12.3',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7738,32,N'12.6',N'12.6',N'12.6',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7739,32,N'12.5',N'12.5',N'12.5',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7740,32,N'12.13',N'12.13',N'12.13',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7741,32,N'12.9',N'12.9',N'12.9',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7742,32,N'12.11',N'12.11',N'12.11',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7743,32,N'11.18',N'11.18',N'11.18',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7744,32,N'11.13',N'11.13',N'11.13',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7745,32,N'11.10',N'11.10',N'11.10',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7746,32,N'11.16',N'11.16',N'11.16',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7747,32,N'11.3',N'11.3',N'11.3',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7748,32,N'11.11',N'11.11',N'11.11',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7749,32,N'9',N'9',N'9',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7750,32,N'9.2',N'9.2',N'9.2',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7751,32,N'9.4',N'9.4',N'9.4',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7752,32,N'9.9',N'9.9',N'9.9',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7753,32,N'10',N'10',N'10',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7754,32,N'Restricted to Aeroplanes on the Bulgarian register',N'Ограничен за самолети включени само в Българския регистър',N'Restricted to Aeroplanes on the Bulgarian register',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7755,32,N'Valid only with qualified PIC in the aircraft with dual controls',N'Valid only with qualified PIC in the aircraft with dual controls',N'Valid only with qualified PIC in the aircraft with dual controls',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7756,32,N'No:Electr. AVC',N'No:Electr. AVC',N'No:Electr. AVC',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7757,32,N'12.8',N'12.8',N'12.8',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7758,32,N'28',N'28',N'28',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7759,32,N'No:Electr:AVC(FAD)',N'No:Electr:AVC(FAD)',N'No:Electr:AVC(FAD)',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7760,32,N'11.15',N'11.15',N'11.15',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7761,32,N'NO:AVC',N'NO:AVC',N'NO:AVC',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7762,32,N'Pressurised aeroplanes',N'Pressurised aeroplanes',N'Pressurised aeroplanes',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7763,32,N'Based on FAA Licence No. CPL(A)-3671277',N'Based on FAA Licence No. CPL(A)-3671277',N'Based on FAA Licence No. CPL(A)-3671277',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7764,32,N'35',N'35',N'35',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7765,32,N'Wooden structure aeroplanes',N'Wooden structure aeroplanes',N'Wooden structure aeroplanes',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7766,32,N'No:Electr. AVC-Line',N'No:Electr. AVC-Line',N'No:Electr. AVC-Line',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7767,32,N'11.19',N'11.19',N'11.19',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7768,32,N'11.20',N'11.20',N'11.20',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7769,32,N'11.21',N'11.21',N'11.21',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7770,32,N'To Metal Structure  AC Aircraft',N'To Metal Structure  AC Aircraft',N'To Metal Structure  AC Aircraft',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7771,32,N'15.4',N'15.4',N'15.4',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7772,32,N'FI(A) VFR only',N'FI(A) VFR only',N'FI(A) VFR only',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7773,32,N'12.15',N'12.15',N'12.15',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7774,32,N'Based on FAA Licence No. CPL(A)-3399155 ',N'Based on FAA Licence No. CPL(A)-3399155 ',N'Based on FAA Licence No. CPL(A)-3399155 ',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7775,32,N'NO:Electr.AVC-Line,FADEC',N'NO:Electr.AVC-Line,FADEC',N'NO:Electr.AVC-Line,FADEC',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7776,32,N'7.5',N'7.5',N'7.5',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7777,32,N'13.3',N'13.3',N'13.3',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7778,32,N'13.5',N'13.5',N'13.5',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7779,32,N'13.8',N'13.8',N'13.8',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7780,32,N'14.2',N'14.2',N'14.2',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7781,32,N'15.1',N'15.1',N'15.1',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7782,32,N'15.12',N'15.12',N'15.12',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7783,32,N'15.16',N'15.16',N'15.16',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7784,32,N'15.19',N'15.19',N'15.19',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7785,32,N'15.21',N'15.21',N'15.21',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7786,32,N'16',N'16',N'16',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7787,32,N'16.13',N'16.13',N'16.13',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7788,32,N'17.1',N'17.1',N'17.1',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7789,32,N'21',N'Radio, communication & radar systems',N'Radio, communication & radar systems',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7790,32,N'27',N'Radio radar systems',N'Radio radar systems',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7791,32,N'29',N'Engine',N'Engine',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7792,32,N'31',N'31',N'31',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7793,32,N'13.2',N'13.2',N'13.2',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7794,32,N'11.5',N'11.5',N'11.5',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7795,32,N'11.6',N'11.6',N'11.6',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7796,32,N'FI(A) for PPL(A) only',N'FI(A) for PPL(A) only',N'FI(A) for PPL(A) only',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7797,32,N'GRAUND CHECK',N'GRAUND CHECK',N'GRAUND CHECK',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7798,32,N'no; electr ; instr.',N'no; electr ; instr.',N'no; electr ; instr.',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7799,32,N'13.12',N'13.12',N'13.12',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7800,32,N'13.14',N'13.14',N'13.14',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7801,32,N'13.16',N'13.16',N'13.16',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7802,32,N'13.18',N'13.18',N'13.18',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7803,32,N'13.19',N'13.19',N'13.19',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7804,32,N'13.20',N'13.20',N'13.20',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7805,32,N'13.21',N'13.21',N'13.21',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7806,32,N'13.22',N'13.22',N'13.22',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7807,32,N'14.3',N'14.3',N'14.3',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7808,32,N'Only valid for flights of Qatar Airways/Qatar',N'Only valid for flights of Qatar Airways/Qatar',N'Only valid for flights of Qatar Airways/Qatar',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7809,32,N'Limited to: Composite structure aeroplanes',N'Limited to: Composite structure aeroplanes',N'Limited to: Composite structure aeroplanes',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7810,32,N'Only valid for flights of Etihad Airways UAE',N'Only valid for flights of Etihad Airways UAE',N'Only valid for flights of Etihad Airways UAE',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7811,32,N'Restricted to Aircraft on the Bulgarian register',N'Restricted to Aircraft on the Bulgarian register',N'Restricted to Aircraft on the Bulgarian register',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7812,32,N'NP',N'НАЦИОНАЛНИ ПРАВА (Валидни само в РБългария)',N'NATIONAL PRIVILEGE (Valid only in Bulgaria)',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7813,32,N'Restricted to KA-26 on the Bulgarian register',N'Ограничен за KA-26 само в Българския регистър',N'Restricted to KA-26 on the Bulgarian register',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7814,32,N'12.7',N'12.7',N'12.7',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7815,32,N'Restricted to AN-26 on the Bulgarian register',N'Ограничен за AN-26 само в Българския регистър',N'Restricted to AN-26 on the Bulgarian register',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7816,32,N'No:Electr. RADIO',N'No:Electr. RADIO',N'No:Electr. RADIO',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7817,32,N'No:Radio',N'No:Radio',N'No:Radio',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7818,32,N'3.2',N'3.2',N'3.2',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7819,32,N'GROUND CHECK',N'GROUND CHECK',N'GROUND CHECK',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7820,32,N'Bulgarian Level 6 Unlimited',N'Bulgarian Level 6 Unlimited',N'Bulgarian Level 6 Unlimited',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7821,32,N'Limited to: Metal structure aeroplanes',N'Limited to: Metal structure aeroplanes',N'Limited to: Metal structure aeroplanes',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7822,32,N'Restricted to Aircraft on the United Arab Emirates register',N'Restricted to Aircraft on the United Arab Emirates register',N'Restricted to Aircraft on the United Arab Emirates register',NULL,NULL,1,N'{}');
INSERT INTO NomValues (NomValueId,NomId,Code,Name,NameAlt,ParentValueId,Alias,IsActive,TextContent) VALUES(7823,32,N'Restricted to MI-8 on the Bulgarian register',N'Restricted to MI-8 on the Bulgarian register',N'Restricted to MI-8 on the Bulgarian register',NULL,NULL,1,N'{}');
GO

SET IDENTITY_INSERT [NomValues] OFF
GO
