INSERT INTO Noms (NomId, Name, Alias) VALUES (1,'Полове','gender');
INSERT INTO Noms (NomId, Name, Alias) VALUES (2,'Държави','countries');
INSERT INTO Noms (NomId, Name, Alias) VALUES (3,'Населени места','cities');
INSERT INTO Noms (NomId, Name, Alias) VALUES (4,'Типове адреси','addressTypes');
INSERT INTO Noms (NomId, Name, Alias) VALUES (5,'Типове персонал','staffTypes');
INSERT INTO Noms (NomId, Name, Alias) VALUES (6,'Категории персонал','employmentCategories');
INSERT INTO Noms (NomId, Name, Alias) VALUES (7,'Степени на образование','graduations');
INSERT INTO Noms (NomId, Name, Alias) VALUES (8,'Учебни заведения','schools');
INSERT INTO Noms (NomId, Name, Alias) VALUES (9,'Направления','directions');
INSERT INTO Noms (NomId, Name, Alias) VALUES (10,'Типове документи','documentTypes');
INSERT INTO Noms (NomId, Name, Alias) VALUES (11,'Роли документи','documentRoles');
INSERT INTO Noms (NomId, Name, Alias) VALUES (12,'Типове документи за самоличност на Физическо лице','personIddocumentTypes');
INSERT INTO Noms (NomId, Name, Alias) VALUES (13,'Роли документи за проверка на Физическо лице','personCheckDocumentRoles');
INSERT INTO Noms (NomId, Name, Alias) VALUES (14,'Типове документи за проверка на Физическо лице','personCheckDocumentTypes');
INSERT INTO Noms (NomId, Name, Alias) VALUES (15,'Типове състояния на Физичеко лице','personStatusTypes');
INSERT INTO Noms (NomId, Name, Alias) VALUES (16,'Издатели на документи - Други','otherDocPublishers');
INSERT INTO Noms (NomId, Name, Alias) VALUES (17,'Издатели на документи - Медицински','medDocPublishers');
INSERT INTO Noms (NomId, Name, Alias) VALUES (18,'Типове ВС за екипажи','ratingTypes');
INSERT INTO Noms (NomId, Name, Alias) VALUES (19,'Групи Класове ВС за екипажи','ratingClassGroups');
INSERT INTO Noms (NomId, Name, Alias) VALUES (20,'Класове ВС за екипажи','ratingClasses');
INSERT INTO Noms (NomId, Name, Alias) VALUES (21,'Подкласове ВС за екипажи','ratingSubClasses');
INSERT INTO Noms (NomId, Name, Alias) VALUES (22,'Групи Разрешения към квалификация','authorizationGroups');
INSERT INTO Noms (NomId, Name, Alias) VALUES (23,'Разрешения към квалификация','authorizations');
INSERT INTO Noms (NomId, Name, Alias) VALUES (24,'Легенда към видове(типове) правоспособност','licenceTypeDictionary');
INSERT INTO Noms (NomId, Name, Alias) VALUES (25,'Видове(типове) правоспособност','licenceTypes');
INSERT INTO Noms (NomId, Name, Alias) VALUES (26,'Индикатори на местоположение','locationIndicators');
INSERT INTO Noms (NomId, Name, Alias) VALUES (27,'Държатели на ТС за ВС','aircraftTCHolders');
INSERT INTO Noms (NomId, Name, Alias) VALUES (28,'Типове ВС','aircraftTypes');
INSERT INTO Noms (NomId, Name, Alias) VALUES (29,'Групи ВС','aircraftTypeGroups');
INSERT INTO Noms (NomId, Name, Alias) VALUES (30,'Категория за АМЛ (Part-66 Category)','aircraftGroup66');
INSERT INTO Noms (NomId, Name, Alias) VALUES (31,'Клас (Part-66 Category)','aircraftClases66');
INSERT INTO Noms (NomId, Name, Alias) VALUES (32,'Ограничения (Part-66)','limitations66');
INSERT INTO Noms (NomId, Name, Alias) VALUES (33,'Класове за медицинска годност','medClasses');
INSERT INTO Noms (NomId, Name, Alias) VALUES (34,'Ограничения за медицинска годност','medLimitation');
INSERT INTO Noms (NomId, Name, Alias) VALUES (35,'Роли в натрупан летателният опит','experienceRoles');
INSERT INTO Noms (NomId, Name, Alias) VALUES (36,'Видове летателен опит','experienceMeasures');
INSERT INTO Noms (NomId, Name, Alias) VALUES (37,'Въздухоплавателни администрации','caa');
INSERT INTO Noms (NomId, Name, Alias) VALUES (38,'Степени на квалификационен клас на Физическо лице','personRatingLevels');
INSERT INTO Noms (NomId, Name, Alias) VALUES (39,'Видове действия относно правоспособност','licenceActions');
INSERT INTO Noms (NomId, Name, Alias) VALUES (40,'Класификатор на организации','organizationTypes');
INSERT INTO Noms (NomId, Name, Alias) VALUES (41,'Видове организации','organizationKinds');
INSERT INTO Noms (NomId, Name, Alias) VALUES (42,'Видове заявления','applicationTypes');
INSERT INTO Noms (NomId, Name, Alias) VALUES (43,'Видове плащания по заявления','applicationpaymentTypes');
INSERT INTO Noms (NomId, Name, Alias) VALUES (44,'Парични единици','currencies');

