print 'Excel Insert DocTypeUnitRoles'
GO

SET IDENTITY_INSERT [DocTypeUnitRoles] ON
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(1,10,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(2,11,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(3,12,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(4,13,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(5,14,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(6,15,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(7,16,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(8,17,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(9,18,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(10,19,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(11,20,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(12,21,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(13,22,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(14,23,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(15,24,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(16,25,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(17,26,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(18,27,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(19,28,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(20,29,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(21,30,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(22,31,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(23,32,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(24,33,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(25,34,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(26,35,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(27,36,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(28,37,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(29,38,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(30,39,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(31,40,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(32,41,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(33,42,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(34,43,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(35,44,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(36,45,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(37,46,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(38,47,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(39,48,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(40,49,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(41,50,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(42,51,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(43,52,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(44,53,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(45,54,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(46,55,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(47,56,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(48,57,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(49,58,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(50,59,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(51,60,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(52,61,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(53,62,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(54,63,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(55,64,1,2,3, 1);
INSERT INTO [DocTypeUnitRoles]([DocTypeUnitRoleId],[DocTypeId],[DocDirectionId],[DocUnitRoleId],[UnitId],[IsActive])VALUES(56,65,1,2,3, 1);
SET IDENTITY_INSERT [DocTypeUnitRoles] OFF
GO

