print 'Excel Insert IrregularityTypes'
GO

SET IDENTITY_INSERT [IrregularityTypes] ON
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(1,1,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(2,1,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(3,1,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(4,1,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(5,1,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(6,1,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(7,1,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(8,2,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(9,2,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(10,2,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(11,2,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(12,2,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(13,2,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(14,2,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(15,3,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(16,3,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(17,3,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(18,3,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(19,3,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(20,3,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(21,3,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(22,4,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(23,4,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(24,4,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(25,4,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(26,4,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(27,4,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(28,4,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(29,5,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(30,5,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(31,5,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(32,5,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(33,5,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(34,5,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(35,5,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(36,6,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(37,6,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(38,6,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(39,6,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(40,6,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(41,6,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(42,6,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(43,7,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(44,7,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(45,7,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(46,7,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(47,7,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(48,7,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(49,7,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(50,8,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(51,8,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(52,8,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(53,8,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(54,8,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(55,8,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(56,8,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(57,9,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(58,9,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(59,9,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(60,9,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(61,9,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(62,9,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(63,9,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(64,10,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(65,10,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(66,10,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(67,10,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(68,10,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(69,10,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(70,10,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(71,11,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(72,11,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(73,11,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(74,11,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(75,11,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(76,11,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(77,11,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(78,12,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(79,12,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(80,12,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(81,12,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(82,12,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(83,12,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(84,12,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(85,13,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(86,13,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(87,13,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(88,13,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(89,13,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(90,13,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(91,13,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(92,14,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(93,14,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(94,14,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(95,14,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(96,14,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(97,14,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(98,14,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(99,15,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(100,15,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(101,15,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(102,15,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(103,15,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(104,15,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(105,15,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(106,16,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(107,16,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(108,16,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(109,16,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(110,16,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(111,16,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(112,16,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(113,17,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(114,17,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(115,17,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(116,17,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(117,17,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(118,17,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(119,17,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(120,18,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(121,18,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(122,18,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(123,18,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(124,18,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(125,18,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(126,18,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(127,19,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(128,19,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(129,19,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(130,19,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(131,19,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(132,19,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(133,19,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(134,20,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(135,20,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(136,20,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(137,20,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(138,20,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(139,20,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(140,20,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(141,21,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(142,21,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(143,21,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(144,21,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(145,21,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(146,21,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(147,21,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(148,22,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(149,22,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(150,22,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(151,22,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(152,22,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(153,22,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(154,22,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(155,23,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(156,23,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(157,23,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(158,23,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(159,23,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(160,23,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(161,23,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(162,24,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(163,24,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(164,24,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(165,24,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(166,24,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(167,24,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(168,24,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(169,25,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(170,25,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(171,25,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(172,25,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(173,25,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(174,25,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(175,25,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(176,26,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(177,26,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(178,26,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(179,26,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(180,26,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(181,26,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(182,26,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(183,27,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(184,27,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(185,27,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(186,27,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(187,27,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(188,27,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(189,27,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(190,28,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(191,28,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(192,28,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(193,28,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(194,28,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(195,28,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(196,28,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(197,29,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(198,29,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(199,29,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(200,29,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(201,29,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(202,29,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(203,29,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(204,30,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(205,30,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(206,30,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(207,30,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(208,30,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(209,30,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(210,30,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(211,31,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(212,31,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(213,31,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(214,31,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(215,31,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(216,31,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(217,31,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(218,32,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(219,32,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(220,32,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(221,32,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(222,32,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(223,32,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(224,32,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(225,33,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(226,33,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(227,33,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(228,33,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(229,33,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(230,33,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(231,33,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(232,34,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(233,34,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(234,34,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(235,34,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(236,34,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(237,34,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(238,34,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(239,35,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(240,35,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(241,35,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(242,35,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(243,35,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(244,35,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(245,35,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(246,36,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(247,36,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(248,36,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(249,36,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(250,36,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(251,36,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(252,36,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(253,37,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(254,37,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(255,37,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(256,37,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(257,37,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(258,37,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(259,37,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(260,38,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(261,38,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(262,38,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(263,38,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(264,38,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(265,38,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(266,38,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(267,39,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(268,39,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(269,39,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(270,39,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(271,39,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(272,39,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(273,39,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(274,40,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(275,40,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(276,40,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(277,40,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(278,40,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(279,40,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(280,40,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(281,41,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(282,41,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(283,41,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(284,41,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(285,41,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(286,41,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(287,41,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(288,42,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(289,42,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(290,42,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(291,42,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(292,42,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(293,42,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(294,42,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(295,43,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(296,43,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(297,43,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(298,43,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(299,43,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(300,43,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(301,43,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(302,44,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(303,44,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(304,44,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(305,44,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(306,44,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(307,44,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(308,44,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(309,45,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(310,45,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(311,45,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(312,45,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(313,45,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(314,45,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(315,45,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(316,46,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(317,46,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(318,46,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(319,46,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(320,46,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(321,46,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(322,46,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(323,47,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(324,47,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(325,47,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(326,47,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(327,47,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(328,47,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(329,47,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(330,48,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(331,48,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(332,48,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(333,48,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(334,48,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(335,48,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(336,48,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(337,49,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(338,49,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(339,49,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(340,49,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(341,49,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(342,49,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(343,49,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(344,50,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(345,50,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(346,50,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(347,50,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(348,50,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(349,50,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(350,50,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(351,51,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(352,51,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(353,51,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(354,51,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(355,51,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(356,51,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(357,51,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(358,52,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(359,52,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(360,52,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(361,52,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(362,52,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(363,52,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(364,52,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(365,53,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(366,53,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(367,53,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(368,53,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(369,53,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(370,53,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(371,53,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(372,54,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(373,54,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(374,54,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(375,54,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(376,54,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(377,54,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(378,54,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(379,55,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(380,55,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(381,55,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(382,55,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(383,55,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(384,55,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(385,55,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(386,56,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(387,56,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(388,56,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(389,56,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(390,56,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(391,56,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(392,56,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(393,57,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(394,57,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(395,57,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(396,57,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(397,57,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(398,57,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(399,57,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(400,58,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(401,58,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(402,58,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(403,58,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(404,58,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(405,58,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(406,58,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(407,59,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(408,59,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(409,59,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(410,59,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(411,59,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(412,59,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(413,59,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(414,60,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(415,60,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(416,60,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(417,60,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(418,60,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(419,60,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(420,60,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(421,61,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(422,61,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(423,61,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(424,61,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(425,61,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(426,61,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(427,61,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(428,62,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(429,62,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(430,62,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(431,62,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(432,62,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(433,62,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(434,62,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(435,63,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(436,63,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(437,63,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(438,63,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(439,63,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(440,63,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(441,63,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(442,64,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(443,64,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(444,64,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(445,64,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(446,64,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(447,64,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(448,64,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(449,65,N'Неизползване или използване на грешен образец',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(450,65,N'Нарушена структура на данни в електронен документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(451,65,N'Невалиден електронен подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(452,65,N'Липса на съответствие между заявено авторство в документа и автора на електронния подпис',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(453,65,N'Липса на данни в подаден документ',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(454,65,N'Липса на указан приложен документ в комплекта',NULL,NULL);
INSERT INTO [IrregularityTypes]([IrregularityTypeId],[DocTypeId],[Name],[Alias],[Description])VALUES(455,65,N'Други проверки, предвидени в нормативен акт',NULL,NULL);
SET IDENTITY_INSERT [IrregularityTypes] OFF
GO

