//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rio.Objects.Enums.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrganizationKindNomenclature {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrganizationKindNomenclature() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rio.Objects.Enums.App_LocalResources.OrganizationKindNomenclature", typeof(OrganizationKindNomenclature).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex.
        /// </summary>
        public static string Complex {
            get {
                return ResourceManager.GetString("Complex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наета по договор организация за ТО.
        /// </summary>
        public static string Hired {
            get {
                return ResourceManager.GetString("Hired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to организация по част М, подчаст F.
        /// </summary>
        public static string MSubpartF {
            get {
                return ResourceManager.GetString("MSubpartF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to организация по част М, подчаст G.
        /// </summary>
        public static string MSubpartG {
            get {
                return ResourceManager.GetString("MSubpartG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Complex.
        /// </summary>
        public static string NonComplex {
            get {
                return ResourceManager.GetString("NonComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Собствена организация за ТО.
        /// </summary>
        public static string Own {
            get {
                return ResourceManager.GetString("Own", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to организация по част 145.
        /// </summary>
        public static string Part145 {
            get {
                return ResourceManager.GetString("Part145", resourceCulture);
            }
        }
    }
}
