PRINT 'Insert instructorExaminerCertificateAttachmentPrivileges'
GO
INSERT [dbo].[Noms] ([Name], [Alias], [Category]) VALUES (N'Права за приложение към сертификат за Проверяващ/Инструктор', N'instructorExaminerCertificateAttachmentPrivileges', N'person')

DECLARE @nomId INT = @@IDENTITY
(select NomValueId from NomValues where Alias = N'Person'      )
INSERT INTO [NomValues]
    ([NomId], [Code]                                 , [Name]                                                                                                                                                                                                                                                                     , [NameAlt]                                                                                                                                                                                              ,[ParentValueId]                                                                                                                                                        , [Alias], [IsActive], [TextContent])
VALUES
-- CRI--
    (@nomId , N'FCL.905.CRI (a)(1)'                  , N'издаване, потвърждаване на валидността и подновяване на квалификация за клас или тип за еднопилотни несложни самолети с ниски летателни характеристики за еднопилотна експлоатация'                                                                                      , N'the issue, revalidation or renewal of a class or type rating for non-complex non-high performance single-pilot aeroplanes in single-pilot operations'                                                , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'CRI')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.CRI (a)(2)'                  , N'квалификация за теглене или фигурен пилотаж за категория самолети'                                                                                                                                                                                                       , N'a towing or aerobatic rating for the aeroplane category'                                                                                                                                             , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'CRI')   , NULL   , 1         , NULL        ),
--FI--
    (@nomId , N'FCL.905.FI (a)'                      , N'летателно обучение за издаване, потвърждаване на валидността и подновяване на PPL, SPL, BPL и LAPL  на самолет'                                                                                                                                                          , N'flight instruction for the issue, revalidation or renewal of a PPL, SPL, BPL and LAPL in the aeroplane'                                                                                              , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'FI')    , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.FI (b)'                      , N'летателно обучение за издаване, потвърждаване на валидността и подновяване на квалификация за клас и тип за еднопилотни, еднодвигателни самолети, с изключение на еднопилотни сложни самолети с високи летателни характеристики'                                         , N'flight instruction for the issue, revalidation or renewal of a class and type ratings for single-pilot, single-engine aeroplanes, except for single-pilot high performance complex aeroplanes'       , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'FI')    , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.FI (c)'                      , N'летателно обучение за CPL за самолет'                                                                                                                                                                                                                                    , N'flight instruction for the CPL in the aeroplanes'                                                                                                                                                    , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'FI')    , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.FI (d)'                      , N'летателно обучение за квалификация за нощни полети'                                                                                                                                                                                                                      , N'flight instruction for the night rating'                                                                                                                                                             , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'FI')    , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.FI (e)'                      , N'етателно обучение за квалификация за теглене или фигурен пилотаж'                                                                                                                                                                                                        , N'flight instruction for a towing or aerobatic rating'                                                                                                                                                 , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'FI')    , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.FI (f)'                      , N'летателно обучение за IR за самолет'                                                                                                                                                                                                                                     , N'flight instruction for an IR in the aeroplane'                                                                                                                                                       , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'FI')    , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.FI (g)'                      , N'летателно обучение за квалификация за клас или тип еднопилотни, многодвигателни самолети, с изключение на еднопилотни сложни самолети с високи летателни характеристики'                                                                                                 , N'flight instruction for a single-pilot multi-engine class or type ratings, except for single-pilot high performance complex aeroplanes'                                                               , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'FI')    , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.FI (h)'                      , N'летателно обучение за сертификат за FI, IRI, CRI, STI или MI'                                                                                                                                                                                                            , N'flight instruction for an FI, IRI, CRI, STI or MI certificate'                                                                                                                                       , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'FI')    , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.FI (i)'                      , N'летателно обучение за MPL'                                                                                                                                                                                                                                               , N'flight instruction for an MPL'                                                                                                                                                                       , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'FI')    , NULL   , 1         , NULL        ),
--FTI--
    (@nomId , N'FCL.905.FTI (a)(1)'                  , N'придобиване на квалификации за летателни изпитания от категория 1 или 2'                                                                                                                                                                                                 , N'the issue of category 1 or 2 flight test ratings, provided he/she holds the relevant category of flight test rating'                                                                                 , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'FTI')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.FTI (a)(2)'                  , N'издаване на сертификат за FTI в рамките на съответната категория квалификация за летателни изпитания'                                                                                                                                                                    , N'the issue of an FTI certificate, within the relevant category of flight test rating'                                                                                                                 , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'FTI')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.FTI (b)'                     , N'Правата на FTI, който притежава квалификация за летателни изпитания от категория 1, включват предоставяне на летателно обучение и във връзка с квалификации за летателни изпитания от категория 2.'                                                                      , N'The privileges of an FTI holding a category 1 flight test rating include the provision of flight instruction also in relation to category 2 flight test ratings'                                     , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'FTI')   , NULL   , 1         , NULL        ),
--IRI--	
    (@nomId , N'FCL.905.IRI (a)'                     , N'издаване, потвърждаване на валидността и подновяване на IR на самолет'                                                                                                                                                                                                   , N'issue, revalidation and renewal of an IR on the aeroplane'                                                                                                                                           , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'IRI')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.IRI (b)'                     , N'основната фаза на обучението на курс за MPL'                                                                                                                                                                                                                             , N'the basic phase of training on an MPL course'                                                                                                                                                        , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'IRI')   , NULL   , 1         , NULL        ),
--MCCI--
    (@nomId , N'FCL.905.MCCI (a)(1)'                 , N'практическата част от курсове по MCC, когато не са съчетани с обучение за придобиване на квалификация за тип'                                                                                                                                                            , N'the practical part of MCC courses when not combined with type rating training'                                                                                                                       , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'MCCI')  , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.MCCI (a)(2)'                 , N'основната фаза на интегрирания курс за обучение за MPL'                                                                                                                                                                                                                  , N'the basic phase of the MPL integrated training course'                                                                                                                                               , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'MCCI')  , NULL   , 1         , NULL        ),
--MI--
    (@nomId , N'FCL.905.MI'                          , N'летателно обучение за придобиване на квалификация за планински терени'                                                                                                                                                                                                   , N'to carry out flight instruction for the issue of a mountain rating'                                                                                                                                  , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'MI')    , NULL   , 1         , NULL        ),
--SFI--
    (@nomId , N'FCL.905.SFI (a)'                     , N'издаване, потвърждаване на валидността и подновяване на IR'                                                                                                                                                                                                              , N'the issue, revalidation and renewal of an IR'                                                                                                                                                        , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'SFI')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.SFI (b)(1)'                  , N'издаване, потвърждаване на валидността и подновяване на квалификации за тип за еднопилотни сложни самолети с високи летателни характеристики за еднопилотна експлоатация'                                                                                                , N'the issue, revalidation and renewal of type ratings for single-pilot high performance complex aeroplanes in single-pilot operations'                                                                 , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'SFI')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.SFI (b)(2)'                  , N'издаване, потвърждаване на валидността и подновяване на квалификации за тип за еднопилотни сложни самолети с високи летателни характеристики за многопилотна експлоатация'                                                                                               , N'the issue, revalidation and renewal of type ratings for single-pilot high performance complex aeroplanes in multi-pilot operations'                                                                  , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'SFI')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.SFI FCL.905.SFI (b)(2)(i)'   , N'MCC'                                                                                                                                                                                                                                                                     , N''                                                                                                                                                                                                    , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'SFI')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.SFI FCL.905.SFI (b)(2)(ii)'  , N'курса за MPL за основната фаза'                                                                                                                                                                                                                                          , N'the MPL course on the basic phase'                                                                                                                                                                   , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'SFI')   , NULL   , 1         , NULL        ),
--STI--
    (@nomId , N'FCL.905.STI (a)(1)'                  , N'летателно обучение на симулатор на самолет за издаване на свидетелство за правоспособност'                                                                                                                                                                              , N'to carry out synthetic flight instruction in the aeroplane for the issue of a licence'                                                                                                                , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'STI')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.STI (a)(2)'                  , N'издаване, потвърждаване на валидността и подновяване на IR и квалификация за клас или тип за еднопилотни ВС, с изключение на еднопилотни сложни самолети с високи летателни характеристики'                                                                             , N'the issue, revalidation or renewal of an IR and a class or type rating for single-pilot aircraft, except for single-pilot high performance complex aeroplanes'                                        , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'STI')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.STI (b)'                     , N'летателно обучение на симулатор по време на обучението по основни летателни умения от интегрирания курс за МРL'                                                                                                                                                         , N'synthetic flight instruction during the core flying skills training of the MPL integrated training course'                                                                                            , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'STI')   , NULL   , 1         , NULL        ),
--TRI--
    (@nomId , N'FCL.905.TRI (a)'                     , N'потвърждаване на валидността и подновяване на IR'                                                                                                                                                                                                                       , N'the revalidation and renewal of IRs'                                                                                                                                                                  , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'TRI')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.TRI (b)'                     , N'издаване на сертификат за TRI или SFI'                                                                                                                                                                                                                                  , N'the issue of a TRI or SFI certificate'                                                                                                                                                                , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'TRI')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.TRI (d)(1)(i)'               , N'издаване, потвърждаване на валидността и подновяване на квалификации за тип за многопилотни самолети'                                                                                                                                                                   , N'the issue, revalidation and renewal of type ratings for multi-pilot aeroplanes'                                                                                                                       , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'TRI')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.TRI (d)(1)(ii)'              , N'издаване, потвърждаване на валидността и подновяване на квалификации за тип за еднопилотни сложни самолети с високи летателни характеристики за многопилотна експлоатация'                                                                                              , N'the issue, revalidation and renewal of type ratings for single-pilot high performance complex aeroplanes in multi-pilot operations'                                                                   , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'TRI')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.TRI (d)(2)'                  , N'обучение по MCC'                                                                                                                                                                                                                                                        , N'MCC training'                                                                                                                                                                                         , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'TRI')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.905.TRI (d)(3)'                  , N'курса за MPL за основната, междинната и напредналата фаза'                                                                                                                                                                                                              , N'the MPL course on the basic, intermediate and advanced phases'                                                                                                                                        , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'TRI')   , NULL   , 1         , NULL        ),
--CRE--
    (@nomId , N'FCL.1005.CRE (a)(1)'                 , N'проверки на уменията за вписване на квалификации за клас и тип'                                                                                                                                                                                                        , N'skill tests for the issue of class and type ratings'                                                                                                                                                   , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'CRE')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.1005.CRE (b)(1)'                 , N'проверки на професионалната подготовка за потвърждаване на валидността или подновяване на квалификация за клас и тип'                                                                                                                                                  , N'proficiency checks for revalidation or renewal of class and type ratings'                                                                                                                              , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'CRE')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.1005.CRE (b)(2)'                 , N'проверки на професионалната подготовка за потвърждаване на валидността и подновяване на квалификация за полети по прибори'                                                                                                                                             , N'proficiency checks for revalidation and renewal of IRs'                                                                                                                                                , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'CRE')   , NULL   , 1         , NULL        ),
--FE--
    (@nomId , N'FCL.1005.FE (a)(1)'                  , N'проверки на уменията за издаване на PPL(A), както и проверки на уменията и проверки на професионалната подготовка за свързаните с него квалификации за клас и тип еднопилотни самолети, с изключение на еднопилотни сложни самолети с високи летателни характеристики'  , N'skill tests for the issue of the PPL(A) and skill tests and proficiency checks for associated single-pilot class and type ratings, except for single-pilot high performance complex aeroplanes'       , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'FE')    , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.1005.FE (a)(2)'                  , N'проверки на уменията за издаване на CPL(A), както и проверки на уменията и проверки на професионалната подготовка за свързаните с него квалификации за клас и тип еднопилотни самолети, с изключение на еднопилотни сложни самолети с високи летателни характеристики'  , N'skill tests for the issue of the CPL(A) and skill tests and proficiency checks for the associated single-pilot class and type ratings, except for single-pilot high performance complex aeroplanes'   , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'FE')    , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.1005.FE (a)(3)'                  , N'проверки на уменията и проверки на професионалната подготовка за квалификации за тип еднопилотни, многодвигателни вертолети, вписани в PPL(H) или CPL(H)'                                                                                                               , N'skill tests and proficiency checks for single-pilot multi-engine helicopter type ratings entered in a PPL(H) or a CPL(H)'                                                                             , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'FE')    , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.1005.FE (a)(4)'                  , N'проверки на уменията и проверки на професионалната подготовка за LAPL(A)'                                                                                                                                                                                               , N'skill tests and proficiency checks for the LAPL(A)'                                                                                                                                                   , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'FE')    , NULL   , 1         , NULL        ),
--FIE--
    (@nomId , N'FCL.1005.FIE (c)'                    , N'оценки на компетентността за издаването, потвърждаването на валидността или подновяването на сертификати за инструктор за съответната дирижабли'                                                                                                                        , N'assessments of competence for the issue, revalidation or renewal of instructor certificates on the airships'                                                                                          , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'FIE')   , NULL   , 1         , NULL        ),
--IRE--
    (@nomId , N'FCL.1005.IRE'                        , N'проверки на уменията за издаване и да извършва проверки на професионалната подготовка за потвърждаване на валидността или за подновяване на квалификацията за полети по прибори'                                                                                        , N'skill tests for the issue, and proficiency checks for the revalidation or renewal of IRs'                                                                                                             , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'IRE')   , NULL   , 1         , NULL        ),
--SFE--
    (@nomId , N'FCL.1005.SFE (b)(1)'                 , N'проверки на уменията и проверки на професионалната подготовка за издаване, потвърждаване на валидността или подновяване на квалификация за тип'                                                                                                                         , N'skill tests and proficiency checks for the issue, revalidation and renewal of type ratings; and'                                                                                                      , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'SFE')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.1005.SFE (b)(2)'                 , N'проверки на професионалната подготовка за потвърждаване на валидността и подновяване на квалификация за полети по прибори'                                                                                                                                              , N'proficiency checks for the revalidation and renewal of IRs'                                                                                                                                           , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'SFE')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.1005.SFE (b)(3)'                 , N'проверки на уменията за издаване на ATPL(H)'                                                                                                                                                                                                                            , N'skill tests for ATPL(H) issue'                                                                                                                                                                        , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'SFE')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.1005.SFE (b)(4)'                 , N'проверки на уменията и проверки на професионалната подготовка за издаване, потвърждаване на валидността или подновяване на сертификат за SFI(H)'                                                                                                                        , N'skill tests and proficiency checks for the issue, revalidation or renewal of an SFI(H) certificate'                                                                                                   , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'SFE')   , NULL   , 1         , NULL        ),
--TRE--
    (@nomId , N'FCL.1005.TRE (a)(1)'                 , N'Проверки на уменията за първоначално издаване на квалификации за тип за самолети'                                                                                                                                                                                       , N'The privileges of a TRE for aeroplanes are to conduct skill tests for the initial issue of type ratings for aeroplanes'                                                                               , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'TRE')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.1005.TRE (a)(2)'                 , N'проверки на професионалната подготовка за потвърждаване на валидността или подновяване на квалификации за тип и IR'                                                                                                                                                     , N'proficiency checks for revalidation or renewal of type and IRs'                                                                                                                                       , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'TRE')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.1005.TRE (a)(3)'                 , N'проверки на уменията за издаване на ATPL(A)'                                                                                                                                                                                                                            , N'skill tests for ATPL(A) issue'                                                                                                                                                                        , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'TRE')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.1005.TRE (a)(4)'                 , N'проверки на уменията за издаване на MPL, при условие че проверяващият отговаря на изискванията на FCL.925'                                                                                                                                                              , N'skill tests for MPL issue, provided that the examiner has complied with the requirements in FCL.925'                                                                                                  , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'TRE')   , NULL   , 1         , NULL        ),
    (@nomId , N'FCL.1005.TRE (a)(5)'                 , N'оценки на компетентността за издаване, потвърждаване на валидността или подновяване на сертификат за TRI или SFI за съответната категория ВС, при условие че проверяващият има поне 3 години опит като TRE'                                                             , N'assessments of competence for the issue, revalidation or renewal of a TRI or SFI certificate in the applicable aircraft category, provided that the examiner has completed at least 3 years as a TRE' , (select NomValueId from NomValues nv join Noms n on nv.NomId = n.NomId where n.Alias = 'instructorExaminerCertificateAttachmentAuthorizations' and nv.Code = 'TRE')   , NULL   , 1         , NULL        )
GO
